#ifndef MASON_C_H
#define MASON_C_H

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct CMason CMason;

typedef struct CMasonNode CMasonNode;

typedef struct CMasonInlineTextSegment {
  float width;
  float ascent;
  float descent;
} CMasonInlineTextSegment;

typedef struct CMasonInlineChildSegment {
  const struct CMasonNode *node;
  float descent;
} CMasonInlineChildSegment;

typedef enum CMasonSegment_Tag {
  Text,
  InlineChild,
} CMasonSegment_Tag;

typedef struct CMasonSegment {
  CMasonSegment_Tag tag;
  union {
    struct {
      struct CMasonInlineTextSegment text;
    };
    struct {
      struct CMasonInlineChildSegment inline_child;
    };
  };
} CMasonSegment;

typedef struct NodeArray {
  void **array;
  uintptr_t length;
} NodeArray;

typedef enum AvailableSpace_Tag {
  Definite,
  MinContent,
  MaxContent,
} AvailableSpace_Tag;

typedef struct AvailableSpace {
  AvailableSpace_Tag tag;
  union {
    struct {
      float definite;
    };
  };
} AvailableSpace;

typedef struct CMasonBuffer {
  uint8_t *data;
  uintptr_t size;
} CMasonBuffer;

typedef struct CMasonMinMax {
  int32_t min_type;
  float min_value;
  int32_t max_type;
  float max_value;
} CMasonMinMax;

struct CMason *mason_init(void);

void mason_clear(struct CMason *mason);

void mason_release(struct CMason *mason);

void mason_print_tree(struct CMason *mason, struct CMasonNode *node);

void mason_set_device_scale(struct CMason *mason, float scale);

void mason_node_set_segments(struct CMason *mason,
                             struct CMasonNode *node,
                             struct CMasonSegment *segments,
                             uintptr_t segments_len);

void mason_node_clear_segments(struct CMason *mason, struct CMasonNode *node);

bool mason_node_is_equal(struct CMasonNode *node_a, struct CMasonNode *node_b);

void mason_node_array_destroy(struct NodeArray *array);

void mason_node_destroy(struct CMasonNode *node);

struct CMasonNode *mason_node_new_image_node(struct CMason *mason);

struct CMasonNode *mason_node_new_node(struct CMason *mason, bool anonymous);

#if !defined(TARGET_OS_ANDROID)
struct CMasonNode *mason_node_new_node_with_context(struct CMason *mason,
                                                    void *measure_data,
                                                    long long (*measure)(const void*,
                                                                         float,
                                                                         float,
                                                                         float,
                                                                         float));
#endif

struct CMasonNode *mason_node_new_node_with_children(struct CMason *mason,
                                                     struct CMasonNode **children,
                                                     uintptr_t children_size);

struct CMasonNode *mason_node_new_text_node(struct CMason *mason, bool anonymous);

#if !defined(TARGET_OS_ANDROID)
struct CMasonNode *mason_node_new_text_node_with_context(struct CMason *mason,
                                                         void *measure_data,
                                                         long long (*measure)(const void*,
                                                                              float,
                                                                              float,
                                                                              float,
                                                                              float));
#endif

struct CMasonNode *mason_node_new_text_node_with_children(struct CMason *mason,
                                                          struct CMasonNode **children,
                                                          uintptr_t children_size);

void *mason_node_layout(struct CMason *mason,
                        struct CMasonNode *node,
                        void *(*layout)(const float*));

void mason_node_compute_wh(struct CMason *mason,
                           struct CMasonNode *node,
                           float width,
                           float height);

void mason_node_compute_size(struct CMason *mason,
                             struct CMasonNode *node,
                             struct AvailableSpace width,
                             struct AvailableSpace height);

void mason_node_compute_max_content(struct CMason *mason, struct CMasonNode *node);

void mason_node_compute_min_content(struct CMason *mason, struct CMasonNode *node);

void mason_node_compute(struct CMason *mason, struct CMasonNode *node);

struct CMasonNode *mason_node_get_child_at(struct CMason *mason,
                                           struct CMasonNode *node,
                                           uintptr_t index);

void mason_node_set_children(struct CMason *mason,
                             struct CMasonNode *node,
                             struct CMasonNode *const *children,
                             uintptr_t children_size);

void mason_node_add_children(struct CMason *mason,
                             struct CMasonNode *node,
                             struct CMasonNode *const *children,
                             uintptr_t children_size);

void mason_node_prepend_children(struct CMason *mason,
                                 struct CMasonNode *node,
                                 struct CMasonNode *const *children,
                                 uintptr_t children_size);

void mason_node_prepend(struct CMason *mason, struct CMasonNode *node, struct CMasonNode *child);

void mason_node_add_child(struct CMason *mason, struct CMasonNode *node, struct CMasonNode *child);

struct CMasonNode *mason_node_replace_child_at(struct CMason *mason,
                                               struct CMasonNode *node,
                                               struct CMasonNode *child,
                                               uintptr_t index);

void mason_node_add_child_at(struct CMason *mason,
                             struct CMasonNode *node,
                             struct CMasonNode *child,
                             uintptr_t index);

void mason_node_insert_child_before(struct CMason *mason,
                                    struct CMasonNode *node,
                                    struct CMasonNode *child,
                                    struct CMasonNode *reference);

void mason_node_insert_child_after(struct CMason *mason,
                                   struct CMasonNode *node,
                                   struct CMasonNode *child,
                                   struct CMasonNode *reference);

bool mason_node_dirty(struct CMason *mason, struct CMasonNode *node);

void mason_node_mark_dirty(struct CMason *mason, struct CMasonNode *node);

bool mason_node_is_children_same(struct CMason *mason,
                                 struct CMasonNode *node,
                                 struct CMasonNode *const *children,
                                 uintptr_t children_size);

void mason_node_remove_children(struct CMason *mason, struct CMasonNode *node);

struct CMasonNode *mason_node_remove_child_at(struct CMason *mason,
                                              struct CMasonNode *node,
                                              uintptr_t index);

struct CMasonNode *mason_node_remove_child(struct CMason *mason,
                                           struct CMasonNode *node,
                                           struct CMasonNode *child);

struct NodeArray *mason_node_get_children(struct CMason *mason, struct CMasonNode *node);

#if !defined(TARGET_OS_ANDROID)
void mason_node_set_context(struct CMason *mason,
                            struct CMasonNode *node,
                            void *measure_data,
                            long long (*measure)(const void*, float, float, float, float));
#endif

#if !defined(TARGET_OS_ANDROID)
void mason_node_remove_context(struct CMason *mason, struct CMasonNode *node);
#endif

#if !defined(TARGET_OS_ANDROID)
void mason_node_set_apple_node(struct CMason *mason, struct CMasonNode *node, void *apple_node);
#endif

void mason_style_update_non_buffer_data(struct CMason *mason,
                                        struct CMasonNode *node,
                                        const char *grid_auto_rows,
                                        const char *grid_auto_columns,
                                        const char *grid_column,
                                        const char *grid_column_start,
                                        const char *grid_column_end,
                                        const char *grid_row,
                                        const char *grid_row_start,
                                        const char *grid_row_end,
                                        const char *grid_template_rows,
                                        const char *grid_template_columns,
                                        const char *grid_area,
                                        const char *grid_template_areas);

void mason_style_set_with_values(struct CMason *mason,
                                 struct CMasonNode *node,
                                 int display,
                                 int position,
                                 int direction,
                                 int flex_direction,
                                 int flex_wrap,
                                 int overflow,
                                 int align_items,
                                 int align_self,
                                 int align_content,
                                 int justify_items,
                                 int justify_self,
                                 int justify_content,
                                 int inset_left_type,
                                 float inset_left_value,
                                 int inset_right_type,
                                 float inset_right_value,
                                 int inset_top_type,
                                 float inset_top_value,
                                 int inset_bottom_type,
                                 float inset_bottom_value,
                                 int margin_left_type,
                                 float margin_left_value,
                                 int margin_right_type,
                                 float margin_right_value,
                                 int margin_top_type,
                                 float margin_top_value,
                                 int margin_bottom_type,
                                 float margin_bottom_value,
                                 int padding_left_type,
                                 float padding_left_value,
                                 int padding_right_type,
                                 float padding_right_value,
                                 int padding_top_type,
                                 float padding_top_value,
                                 int padding_bottom_type,
                                 float padding_bottom_value,
                                 int border_left_type,
                                 float border_left_value,
                                 int border_right_type,
                                 float border_right_value,
                                 int border_top_type,
                                 float border_top_value,
                                 int border_bottom_type,
                                 float border_bottom_value,
                                 float flex_grow,
                                 float flex_shrink,
                                 int flex_basis_type,
                                 float flex_basis_value,
                                 int width_type,
                                 float width_value,
                                 int height_type,
                                 float height_value,
                                 int min_width_type,
                                 float min_width_value,
                                 int min_height_type,
                                 float min_height_value,
                                 int max_width_type,
                                 float max_width_value,
                                 int max_height_type,
                                 float max_height_value,
                                 int gap_row_type,
                                 float gap_row_value,
                                 int gap_column_type,
                                 float gap_column_value,
                                 float aspect_ratio,
                                 const char *grid_auto_rows,
                                 const char *grid_auto_columns,
                                 int grid_auto_flow,
                                 const char *grid_column,
                                 const char *grid_column_start,
                                 const char *grid_column_end,
                                 const char *grid_row,
                                 const char *grid_row_start,
                                 const char *grid_row_end,
                                 const char *grid_template_rows,
                                 const char *grid_template_columns,
                                 int32_t overflow_x,
                                 int32_t overflow_y,
                                 float scrollbar_width,
                                 int32_t text_align,
                                 int32_t box_sizing,
                                 const char *grid_area,
                                 const char *grid_template_areas);

void mason_style_release_style_buffer(struct CMasonBuffer *buffer);

struct CMasonBuffer *mason_style_get_style_buffer(struct CMason *mason, struct CMasonNode *node);

void *mason_style_get_style_buffer_apple(struct CMason *mason, struct CMasonNode *node);

char *mason_style_get_grid_area_css(struct CMason *mason, struct CMasonNode *node);

char *mason_style_get_grid_template_areas_css(struct CMason *mason, struct CMasonNode *node);

char *mason_style_get_grid_auto_rows_css(struct CMason *mason, struct CMasonNode *node);

char *mason_style_get_grid_auto_columns_css(struct CMason *mason, struct CMasonNode *node);

char *mason_style_get_grid_column_css(struct CMason *mason, struct CMasonNode *node);

char *mason_style_get_grid_column_start_css(struct CMason *mason, struct CMasonNode *node);

char *mason_style_get_grid_column_end_css(struct CMason *mason, struct CMasonNode *node);

char *mason_style_get_grid_row_css(struct CMason *mason, struct CMasonNode *node);

char *mason_style_get_grid_row_start_css(struct CMason *mason, struct CMasonNode *node);

char *mason_style_get_grid_row_end_css(struct CMason *mason, struct CMasonNode *node);

char *mason_style_get_grid_template_rows_css(struct CMason *mason, struct CMasonNode *node);

char *mason_style_get_grid_template_columns_css(struct CMason *mason, struct CMasonNode *node);

struct CMasonMinMax mason_util_create_track_sizing_function_with_type_value(int32_t track_type,
                                                                            float track_value);

void mason_util_destroy_string(char *string);

#endif  /* MASON_C_H */
