#!/usr/bin/env node
// Generate the JSX intrinsic-element typings from the element registry.
//
// The registry (packages/nativescript-masonkit/elements.ts) is the single source
// of truth for which tags exist; hand-maintained JSX typings drift from it
// immediately — demo-react's listed 4 tags out of ~60. This reads the tag list
// straight out of `web.ts`'s @CSSType decorators and the registry's own mason
// element table, so the two can't disagree.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '../../..');
const WEB_TS = resolve(root, 'packages/nativescript-masonkit/web.ts');
const ELEMENTS_TS = resolve(root, 'packages/nativescript-masonkit/elements.ts');

// demo-react only: demo-solid and demo-angular get their intrinsics from
// @nativescript-dom/*-types, and a second global JSX.IntrinsicElements would
// merge into those and clash on any tag they type more precisely than `any`.
const OUT = [{ path: 'apps/demo-react/src/jsx.d.ts', react: true }];

function tags() {
  const web = readFileSync(WEB_TS, 'utf8');
  const found = new Set();
  for (const [, tag] of web.matchAll(/@CSSType\('([^']+)'\)/g)) found.add(tag);

  // MasonKit's own widgets come from the registry's MASON_ELEMENTS table, and
  // are registered lowercased by every framework integration.
  const elements = readFileSync(ELEMENTS_TS, 'utf8');
  const table = /MASON_ELEMENTS[^=]*=\s*\[([\s\S]*?)\n\]/.exec(elements);
  if (table) {
    for (const [, name] of table[1].matchAll(/\[\s*'([^']+)'/g)) found.add(name.toLowerCase());
  }
  return [...found].sort();
}

function render(list, react) {
  const body = list.map((tag) => `      ${/^[a-z][a-z0-9]*$/.test(tag) ? tag : `'${tag}'`}: any;`).join('\n');
  const block = `declare global {
  namespace JSX {
    interface IntrinsicElements {
${body}
    }
  }
}`;
  const reactBlock = react
    ? `

declare module 'react' {
  namespace JSX {
    interface IntrinsicElements {
${body}
    }
  }
}`
    : '';
  return `// GENERATED by tools/scripts/gen-jsx-types/generate.mjs — do not edit.
// Run \`npm run gen:jsx-types\` after changing the element registry.
//
// Every tag mason registers, so a pasted snippet typechecks. Loosely typed as
// \`any\`: giving each tag its real prop and style shape is worthwhile but is a
// separate piece of work, and \`any\` is still strictly better than a tag that
// does not exist at all.
${block}${reactBlock}

export {};
`;
}

const list = tags();
const check = process.argv.includes('--check');
let failed = false;

for (const { path, react } of OUT) {
  const full = resolve(root, path);
  const next = render(list, react);
  let current = '';
  try {
    current = readFileSync(full, 'utf8');
  } catch {
    // Not written yet.
  }
  if (check) {
    if (current !== next) {
      console.error(`${path} is out of date — run: npm run gen:jsx-types`);
      failed = true;
    }
    continue;
  }
  if (current !== next) {
    writeFileSync(full, next);
    console.log(`wrote ${path} (${list.length} tags)`);
  } else {
    console.log(`${path} already up to date (${list.length} tags)`);
  }
}

process.exit(failed ? 1 : 0);
