[package]
name = "mason-core"
version = "0.1.0"
edition = "2021"

[dependencies]
taffy = { git="https://github.com/DioxusLabs/taffy.git", rev="563d5dc"}
#taffy = { version = "0.3.18"}

[target.'cfg(target_os = "android")'.dependencies]
jni = "0.21.1"
