// GENERATED by tools/scripts/gen-jsx-types/generate.mjs — do not edit.
// Run `npm run gen:jsx-types` after changing the element registry.
//
// Every tag mason registers, so a pasted snippet typechecks. Loosely typed as
// `any`: giving each tag its real prop and style shape is worthwhile but is a
// separate piece of work, and `any` is still strictly better than a tag that
// does not exist at all.
declare global {
  namespace JSX {
    interface IntrinsicElements {
      a: any;
      abbr: any;
      address: any;
      article: any;
      aside: any;
      b: any;
      bdi: any;
      bdo: any;
      blockquote: any;
      br: any;
      button: any;
      cite: any;
      code: any;
      dd: any;
      del: any;
      details: any;
      dfn: any;
      div: any;
      dl: any;
      dt: any;
      em: any;
      fieldset: any;
      figcaption: any;
      figure: any;
      footer: any;
      form: any;
      h1: any;
      h2: any;
      h3: any;
      h4: any;
      h5: any;
      h6: any;
      header: any;
      hgroup: any;
      hr: any;
      i: any;
      img: any;
      input: any;
      ins: any;
      kbd: any;
      label: any;
      legend: any;
      li: any;
      main: any;
      mark: any;
      nav: any;
      ol: any;
      output: any;
      p: any;
      picture: any;
      pre: any;
      q: any;
      s: any;
      samp: any;
      scroll: any;
      section: any;
      small: any;
      span: any;
      strong: any;
      sub: any;
      summary: any;
      sup: any;
      text: any;
      textarea: any;
      time: any;
      u: any;
      ul: any;
      var: any;
      view: any;
    }
  }
}

declare module 'react' {
  namespace JSX {
    interface IntrinsicElements {
      a: any;
      abbr: any;
      address: any;
      article: any;
      aside: any;
      b: any;
      bdi: any;
      bdo: any;
      blockquote: any;
      br: any;
      button: any;
      cite: any;
      code: any;
      dd: any;
      del: any;
      details: any;
      dfn: any;
      div: any;
      dl: any;
      dt: any;
      em: any;
      fieldset: any;
      figcaption: any;
      figure: any;
      footer: any;
      form: any;
      h1: any;
      h2: any;
      h3: any;
      h4: any;
      h5: any;
      h6: any;
      header: any;
      hgroup: any;
      hr: any;
      i: any;
      img: any;
      input: any;
      ins: any;
      kbd: any;
      label: any;
      legend: any;
      li: any;
      main: any;
      mark: any;
      nav: any;
      ol: any;
      output: any;
      p: any;
      picture: any;
      pre: any;
      q: any;
      s: any;
      samp: any;
      scroll: any;
      section: any;
      small: any;
      span: any;
      strong: any;
      sub: any;
      summary: any;
      sup: any;
      text: any;
      textarea: any;
      time: any;
      u: any;
      ul: any;
      var: any;
      view: any;
    }
  }
}

export {};
