#ifndef CBINDGEN_BINDINGS_H
#define CBINDGEN_BINDINGS_H

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef enum CMasonDimensionType {
  CMasonDimensionTypeAuto,
  CMasonDimensionTypePoints,
  CMasonDimensionTypePercent,
} CMasonDimensionType;

typedef enum CMasonGridPlacementType {
  CMasonGridPlacementTypeAuto,
  CMasonGridPlacementTypeLine,
  CMasonGridPlacementTypeSpan,
} CMasonGridPlacementType;

typedef enum CMasonLengthPercentageAutoType {
  CMasonLengthPercentageAutoTypeAuto,
  CMasonLengthPercentageAutoTypePoints,
  CMasonLengthPercentageAutoTypePercent,
} CMasonLengthPercentageAutoType;

typedef enum CMasonLengthPercentageType {
  CMasonLengthPercentageTypePoints,
  CMasonLengthPercentageTypePercent,
} CMasonLengthPercentageType;

typedef struct Vec_CMasonMinMax Vec_CMasonMinMax;

typedef struct Vec_CMasonNonRepeatedTrackSizingFunction Vec_CMasonNonRepeatedTrackSizingFunction;

typedef struct Vec_CMasonTrackSizingFunction Vec_CMasonTrackSizingFunction;

typedef struct CMasonMinMax {
  int32_t min_type;
  float min_value;
  int32_t max_type;
  float max_value;
} CMasonMinMax;

typedef struct CMasonGridPlacement {
  int16_t value;
  enum CMasonGridPlacementType value_type;
} CMasonGridPlacement;

typedef struct CMasonDimension {
  float value;
  enum CMasonDimensionType value_type;
} CMasonDimension;

typedef struct CMasonLengthPercentageAuto {
  float value;
  enum CMasonLengthPercentageAutoType value_type;
} CMasonLengthPercentageAuto;

typedef struct CMasonLengthPercentage {
  float value;
  enum CMasonLengthPercentageType value_type;
} CMasonLengthPercentage;

typedef struct CMasonLengthPercentageSize {
  struct CMasonLengthPercentage width;
  struct CMasonLengthPercentage height;
} CMasonLengthPercentageSize;

typedef struct CMasonNonRepeatedTrackSizingFunctionArray {
  struct CMasonMinMax *array;
  uintptr_t length;
} CMasonNonRepeatedTrackSizingFunctionArray;

typedef enum CMasonTrackSizingFunction_Tag {
  Single,
  Repeat,
} CMasonTrackSizingFunction_Tag;

typedef struct Repeat_Body {
  int32_t _0;
  uint16_t _1;
  struct CMasonNonRepeatedTrackSizingFunctionArray *_2;
} Repeat_Body;

typedef struct CMasonTrackSizingFunction {
  CMasonTrackSizingFunction_Tag tag;
  union {
    struct {
      struct CMasonMinMax single;
    };
    Repeat_Body repeat;
  };
} CMasonTrackSizingFunction;

typedef struct CMasonTrackSizingFunctionArray {
  struct CMasonTrackSizingFunction *array;
  uintptr_t length;
} CMasonTrackSizingFunctionArray;

int64_t mason_init(void);

int64_t mason_init_with_capacity(int32_t capacity);

void mason_clear(int64_t mason);

void mason_util_create_non_repeated_track_sizing_function(struct CMasonMinMax min_max,
                                                          intptr_t index,
                                                          struct Vec_CMasonNonRepeatedTrackSizingFunction *store);

void mason_util_create_single_track_sizing_function(struct CMasonMinMax min_max,
                                                    intptr_t index,
                                                    struct Vec_CMasonTrackSizingFunction *store);

void mason_util_create_auto_repeating_track_sizing_function(int32_t grid_track_repetition,
                                                            uint16_t grid_track_repetition_count,
                                                            struct Vec_CMasonMinMax values,
                                                            intptr_t index,
                                                            struct Vec_CMasonTrackSizingFunction *store);

int32_t mason_style_get_grid_auto_flow(int64_t style);

void mason_style_set_grid_auto_flow(int64_t style, int32_t value);

struct CMasonGridPlacement mason_style_get_grid_column_start(int64_t style);

void mason_style_set_grid_area(int64_t style,
                               struct CMasonGridPlacement row_start,
                               struct CMasonGridPlacement row_end,
                               struct CMasonGridPlacement column_start,
                               struct CMasonGridPlacement column_end);

void mason_style_set_grid_column(int64_t style,
                                 struct CMasonGridPlacement start,
                                 struct CMasonGridPlacement end);

void mason_style_set_grid_column_start(int64_t style, struct CMasonGridPlacement value);

struct CMasonGridPlacement mason_style_get_grid_column_end(int64_t style);

void mason_style_set_grid_column_end(int64_t style, struct CMasonGridPlacement value);

struct CMasonGridPlacement mason_style_get_grid_row_start(int64_t style);

void mason_style_set_grid_row(int64_t style,
                              struct CMasonGridPlacement start,
                              struct CMasonGridPlacement end);

void mason_style_set_grid_row_start(int64_t style, struct CMasonGridPlacement value);

struct CMasonGridPlacement mason_style_get_grid_row_end(int64_t style);

void mason_style_set_grid_row_end(int64_t style, struct CMasonGridPlacement value);

void mason_style_set_width(int64_t style, float value, enum CMasonDimensionType value_type);

struct CMasonDimension mason_style_get_width(int64_t style);

void mason_style_set_height(int64_t style, float value, enum CMasonDimensionType value_type);

struct CMasonDimension mason_style_get_height(int64_t style);

void mason_node_mark_dirty(int64_t mason, int64_t node);

bool mason_node_dirty(int64_t mason, int64_t node);

void mason_style_set_display(int64_t style, int32_t display);

int32_t mason_style_get_display(int64_t style);

void mason_node_compute(int64_t mason, int64_t node);

void mason_node_compute_min_content(int64_t mason, int64_t node);

void mason_node_compute_max_content(int64_t mason, int64_t node);

void mason_node_compute_wh(int64_t mason, int64_t node, float width, float height);

int32_t mason_style_get_position(int64_t style);

void mason_style_set_position(int64_t style, int32_t value);

int32_t mason_style_get_flex_wrap(int64_t style);

void mason_style_set_flex_wrap(int64_t style, int32_t value);

int32_t mason_style_get_align_items(int64_t style);

void mason_style_set_align_items(int64_t style, int32_t value);

int32_t mason_style_get_align_self(int64_t style);

void mason_style_set_align_self(int64_t style, int32_t value);

int32_t mason_style_get_align_content(int64_t style);

void mason_style_set_align_content(int64_t style, int32_t value);

int32_t mason_style_get_justify_items(int64_t style);

void mason_style_set_justify_items(int64_t style, int32_t value);

int32_t mason_style_get_justify_self(int64_t style);

void mason_style_set_justify_self(int64_t style, int32_t value);

int32_t mason_style_get_justify_content(int64_t style);

void mason_style_set_justify_content(int64_t style, int32_t value);

void mason_style_set_inset(int64_t style,
                           float value,
                           enum CMasonLengthPercentageAutoType value_type);

void mason_style_set_inset_lrtb(int64_t style,
                                float left_value,
                                enum CMasonLengthPercentageAutoType left_value_type,
                                float right_value,
                                enum CMasonLengthPercentageAutoType right_value_type,
                                float top_value,
                                enum CMasonLengthPercentageAutoType top_value_type,
                                float bottom_value,
                                enum CMasonLengthPercentageAutoType bottom_value_type);

struct CMasonLengthPercentageAuto mason_style_get_inset_left(int64_t style);

void mason_style_set_inset_left(int64_t style,
                                float value,
                                enum CMasonLengthPercentageAutoType value_type);

struct CMasonLengthPercentageAuto mason_style_get_inset_right(int64_t style);

void mason_style_set_inset_right(int64_t style,
                                 float value,
                                 enum CMasonLengthPercentageAutoType value_type);

struct CMasonLengthPercentageAuto mason_style_get_inset_top(int64_t style);

void mason_style_set_inset_top(int64_t style,
                               float value,
                               enum CMasonLengthPercentageAutoType value_type);

struct CMasonLengthPercentageAuto mason_style_get_inset_bottom(int64_t style);

void mason_style_set_inset_bottom(int64_t style,
                                  float value,
                                  enum CMasonLengthPercentageAutoType value_type);

void mason_style_set_margin(int64_t style,
                            float value,
                            enum CMasonLengthPercentageAutoType value_type);

struct CMasonLengthPercentageAuto mason_style_get_margin_left(int64_t style);

void mason_style_set_margin_left(int64_t style,
                                 float value,
                                 enum CMasonLengthPercentageAutoType value_type);

struct CMasonLengthPercentageAuto mason_style_get_margin_right(int64_t style);

void mason_style_set_margin_right(int64_t style,
                                  float value,
                                  enum CMasonLengthPercentageAutoType value_type);

struct CMasonLengthPercentageAuto mason_style_get_margin_top(int64_t style);

void mason_style_set_margin_top(int64_t style,
                                float value,
                                enum CMasonLengthPercentageAutoType value_type);

struct CMasonLengthPercentageAuto mason_style_get_margin_bottom(int64_t style);

void mason_style_set_margin_bottom(int64_t style,
                                   float value,
                                   enum CMasonLengthPercentageAutoType value_type);

void mason_style_set_border(int64_t style, float value, enum CMasonLengthPercentageType value_type);

struct CMasonLengthPercentage mason_style_get_border_left(int64_t style);

void mason_style_set_border_left(int64_t style,
                                 float value,
                                 enum CMasonLengthPercentageType value_type);

struct CMasonLengthPercentage mason_style_get_border_right(int64_t style);

void mason_style_set_border_right(int64_t style,
                                  float value,
                                  enum CMasonLengthPercentageType value_type);

struct CMasonLengthPercentage mason_style_get_border_top(int64_t style);

void mason_style_set_border_top(int64_t style,
                                float value,
                                enum CMasonLengthPercentageType value_type);

struct CMasonLengthPercentage mason_style_get_border_bottom(int64_t style);

void mason_style_set_border_bottom(int64_t style,
                                   float value,
                                   enum CMasonLengthPercentageType value_type);

void mason_style_set_flex_grow(int64_t style, float grow);

float mason_style_get_flex_grow(int64_t style);

void mason_style_set_flex_shrink(int64_t style, float shrink);

float mason_style_get_flex_shrink(int64_t style);

struct CMasonDimension mason_style_get_flex_basis(int64_t style);

void mason_style_set_flex_basis(int64_t style, float value, enum CMasonDimensionType value_type);

struct CMasonLengthPercentageSize mason_style_get_gap(int64_t style);

void mason_style_set_gap(int64_t style,
                         float width_value,
                         enum CMasonLengthPercentageType width_type,
                         float height_value,
                         enum CMasonLengthPercentageType height_type);

void mason_style_set_row_gap(int64_t style,
                             float value,
                             enum CMasonLengthPercentageType value_type);

struct CMasonLengthPercentage mason_style_get_row_gap(int64_t style);

void mason_style_set_column_gap(int64_t style,
                                float value,
                                enum CMasonLengthPercentageType value_type);

struct CMasonLengthPercentage mason_style_get_column_gap(int64_t style);

void mason_style_set_aspect_ratio(int64_t style, float ratio);

float mason_style_get_aspect_ratio(int64_t style);

void mason_style_set_padding(int64_t style,
                             float value,
                             enum CMasonLengthPercentageType value_type);

struct CMasonLengthPercentage mason_style_get_padding_left(int64_t style);

void mason_style_set_padding_left(int64_t style,
                                  float value,
                                  enum CMasonLengthPercentageType value_type);

struct CMasonLengthPercentage mason_style_get_padding_right(int64_t style);

void mason_style_set_padding_right(int64_t style,
                                   float value,
                                   enum CMasonLengthPercentageType value_type);

struct CMasonLengthPercentage mason_style_get_padding_top(int64_t style);

void mason_style_set_padding_top(int64_t style,
                                 float value,
                                 enum CMasonLengthPercentageType value_type);

struct CMasonLengthPercentage mason_style_get_padding_bottom(int64_t style);

void mason_style_set_padding_bottom(int64_t style,
                                    float value,
                                    enum CMasonLengthPercentageType value_type);

int32_t mason_style_get_flex_direction(int64_t style);

void mason_style_set_flex_direction(int64_t style, int32_t value);

struct CMasonDimension mason_style_get_min_width(int64_t style);

void mason_style_set_min_width(int64_t style, float value, enum CMasonDimensionType value_type);

struct CMasonDimension mason_style_get_min_height(int64_t style);

void mason_style_set_min_height(int64_t style, float value, enum CMasonDimensionType value_type);

struct CMasonDimension mason_style_get_max_width(int64_t style);

void mason_style_set_max_width(int64_t style, float value, enum CMasonDimensionType value_type);

struct CMasonDimension mason_style_get_max_height(int64_t style);

void mason_style_set_max_height(int64_t style, float value, enum CMasonDimensionType value_type);

void mason_node_update_and_set_style(int64_t mason, int64_t node, int64_t style);

void mason_style_set_scrollbar_width(int64_t style, float value);

float mason_style_get_scrollbar_width(int64_t style);

void mason_style_set_overflow(int64_t style, int32_t value);

void mason_style_set_overflow_x(int64_t style, int32_t value);

int32_t mason_style_get_overflow_x(int64_t style);

void mason_style_set_overflow_y(int64_t style, int32_t value);

int32_t mason_style_get_overflow_y(int64_t style);

struct CMasonNonRepeatedTrackSizingFunctionArray *mason_style_get_grid_auto_rows(int64_t style);

void mason_destroy_track_sizing_function_array(struct CMasonTrackSizingFunctionArray *array);

struct CMasonNonRepeatedTrackSizingFunctionArray *mason_style_get_grid_auto_columns(int64_t style);

void mason_style_set_grid_auto_rows(int64_t style,
                                    struct CMasonNonRepeatedTrackSizingFunctionArray *value);

void mason_style_set_grid_auto_columns(int64_t style,
                                       struct CMasonNonRepeatedTrackSizingFunctionArray *value);

struct CMasonTrackSizingFunctionArray *mason_style_get_grid_template_rows(int64_t style);

struct CMasonTrackSizingFunctionArray *mason_style_get_grid_template_columns(int64_t style);

void mason_style_set_grid_template_rows(int64_t style,
                                        struct CMasonTrackSizingFunctionArray *value);

void mason_style_set_grid_template_columns(int64_t style,
                                           struct CMasonTrackSizingFunctionArray *value);

void mason_style_update_with_values(int64_t style,
                                    int display,
                                    int position_type,
                                    int direction,
                                    int flex_direction,
                                    int flex_wrap,
                                    int overflow,
                                    int align_items,
                                    int align_self,
                                    int align_content,
                                    int justify_items,
                                    int justify_self,
                                    int justify_content,
                                    int inset_left_type,
                                    float inset_left_value,
                                    int inset_right_type,
                                    float inset_right_value,
                                    int inset_top_type,
                                    float inset_top_value,
                                    int inset_bottom_type,
                                    float inset_bottom_value,
                                    int margin_left_type,
                                    float margin_left_value,
                                    int margin_right_type,
                                    float margin_right_value,
                                    int margin_top_type,
                                    float margin_top_value,
                                    int margin_bottom_type,
                                    float margin_bottom_value,
                                    int padding_left_type,
                                    float padding_left_value,
                                    int padding_right_type,
                                    float padding_right_value,
                                    int padding_top_type,
                                    float padding_top_value,
                                    int padding_bottom_type,
                                    float padding_bottom_value,
                                    int border_left_type,
                                    float border_left_value,
                                    int border_right_type,
                                    float border_right_value,
                                    int border_top_type,
                                    float border_top_value,
                                    int border_bottom_type,
                                    float border_bottom_value,
                                    float flex_grow,
                                    float flex_shrink,
                                    int flex_basis_type,
                                    float flex_basis_value,
                                    int width_type,
                                    float width_value,
                                    int height_type,
                                    float height_value,
                                    int min_width_type,
                                    float min_width_value,
                                    int min_height_type,
                                    float min_height_value,
                                    int max_width_type,
                                    float max_width_value,
                                    int max_height_type,
                                    float max_height_value,
                                    int32_t gap_row_type,
                                    float gap_row_value,
                                    int32_t gap_column_type,
                                    float gap_column_value,
                                    float aspect_ratio,
                                    struct CMasonNonRepeatedTrackSizingFunctionArray *grid_auto_rows,
                                    struct CMasonNonRepeatedTrackSizingFunctionArray *grid_auto_columns,
                                    int32_t grid_auto_flow,
                                    int32_t grid_column_start_type,
                                    int16_t grid_column_start_value,
                                    int32_t grid_column_end_type,
                                    int16_t grid_column_end_value,
                                    int32_t grid_row_start_type,
                                    int16_t grid_row_start_value,
                                    int32_t grid_row_end_type,
                                    int16_t grid_row_end_value,
                                    struct CMasonTrackSizingFunctionArray *grid_template_rows,
                                    struct CMasonTrackSizingFunctionArray *grid_template_columns,
                                    int32_t overflow_x,
                                    int32_t overflow_y,
                                    float scrollbar_width);

struct CMasonMinMax mason_util_create_non_repeated_track_sizing_function_with_type_value(int32_t track_type,
                                                                                         float track_value);

char *mason_util_parse_non_repeated_track_sizing_function(struct CMasonNonRepeatedTrackSizingFunctionArray *value);

char *mason_util_parse_auto_repeating_track_sizing_function(struct CMasonTrackSizingFunctionArray *value);

void mason_util_destroy_string(char *string);

#endif /* CBINDGEN_BINDINGS_H */
