#ifndef MASON_ANDROID_H
#define MASON_ANDROID_H

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

void mason_node_update_and_set_style_android(int64_t mason, int64_t node, int64_t style);

#endif /* MASON_ANDROID_H */
