#ifndef MASON_C_H
#define MASON_C_H

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct CMason CMason;

typedef struct CMasonNode CMasonNode;

typedef struct CMasonInlineTextSegment {
  float width;
  float ascent;
  float descent;
} CMasonInlineTextSegment;

typedef struct CMasonInlineChildSegment {
  const struct CMasonNode *node;
  float descent;
} CMasonInlineChildSegment;

typedef enum CMasonSegment_Tag {
  Text,
  InlineChild,
  LineBreak,
} CMasonSegment_Tag;

typedef struct CMasonSegment {
  CMasonSegment_Tag tag;
  union {
    struct {
      struct CMasonInlineTextSegment text;
    };
    struct {
      struct CMasonInlineChildSegment inline_child;
    };
  };
} CMasonSegment;

typedef struct NodeArray {
  void **array;
  uintptr_t length;
} NodeArray;

typedef struct CMasonBuffer {
  uint8_t *data;
  uintptr_t size;
} CMasonBuffer;

typedef enum AvailableSpace_Tag {
  Definite,
  MinContent,
  MaxContent,
} AvailableSpace_Tag;

typedef struct AvailableSpace {
  AvailableSpace_Tag tag;
  union {
    struct {
      float definite;
    };
  };
} AvailableSpace;

typedef struct CMasonMinMax {
  int32_t min_type;
  float min_value;
  int32_t max_type;
  float max_value;
} CMasonMinMax;

struct CMason *mason_init(void);

void mason_clear(struct CMason *mason);

void mason_release(struct CMason *mason);

void mason_print_tree(struct CMason *mason, struct CMasonNode *node);

void mason_set_device_scale(struct CMason *mason, float scale);

void *mason_get_buffer(struct CMason *mason, int handle);

void mason_node_set_segments(struct CMason *mason,
                             struct CMasonNode *node,
                             struct CMasonSegment *segments,
                             uintptr_t segments_len);

void mason_node_clear_segments(struct CMason *mason, struct CMasonNode *node);

bool mason_node_is_equal(struct CMasonNode *node_a, struct CMasonNode *node_b);

void mason_node_array_destroy(struct NodeArray *array);

void mason_node_destroy(struct CMasonNode *node);

struct CMasonNode *mason_node_new_image_node(struct CMason *mason);

struct CMasonNode *mason_node_new_node(struct CMason *mason, bool anonymous);

#if !defined(TARGET_OS_ANDROID)
struct CMasonNode *mason_node_new_node_with_context(struct CMason *mason,
                                                    void *measure_data,
                                                    long long (*measure)(const void*,
                                                                         float,
                                                                         float,
                                                                         float,
                                                                         float));
#endif

struct CMasonNode *mason_node_new_node_with_children(struct CMason *mason,
                                                     struct CMasonNode **children,
                                                     uintptr_t children_size);

struct CMasonNode *mason_node_new_text_node(struct CMason *mason, bool anonymous);

#if !defined(TARGET_OS_ANDROID)
struct CMasonNode *mason_node_new_text_node_with_context(struct CMason *mason,
                                                         void *measure_data,
                                                         long long (*measure)(const void*,
                                                                              float,
                                                                              float,
                                                                              float,
                                                                              float));
#endif

struct CMasonNode *mason_node_new_text_node_with_children(struct CMason *mason,
                                                          struct CMasonNode **children,
                                                          uintptr_t children_size);

struct CMasonNode *mason_node_new_line_break_node(struct CMason *mason);

#if !defined(TARGET_OS_ANDROID)
struct CMasonNode *mason_node_new_line_break_node_with_context(struct CMason *mason,
                                                               void *measure_data,
                                                               long long (*measure)(const void*,
                                                                                    float,
                                                                                    float,
                                                                                    float,
                                                                                    float));
#endif

struct CMasonNode *mason_node_new_list_item_node(struct CMason *mason);

#if !defined(TARGET_OS_ANDROID)
struct CMasonNode *mason_node_new_list_item_node_with_context(struct CMason *mason,
                                                              void *measure_data,
                                                              long long (*measure)(const void*,
                                                                                   float,
                                                                                   float,
                                                                                   float,
                                                                                   float));
#endif

void *mason_node_layout(struct CMason *mason, struct CMasonNode *node, void *(*layout)(const float*,
                                                                                       uintptr_t));

void *mason_node_get_float_rects(struct CMason *mason,
                                 struct CMasonNode *node,
                                 void *(*callback)(const float*));

struct CMasonBuffer *mason_node_get_float_rects_buffer(struct CMason *mason,
                                                       struct CMasonNode *node);

void mason_node_release_float_rects_buffer(struct CMasonBuffer *buffer);

void mason_node_compute_wh(struct CMason *mason,
                           struct CMasonNode *node,
                           float width,
                           float height);

void mason_node_compute_size(struct CMason *mason,
                             struct CMasonNode *node,
                             struct AvailableSpace width,
                             struct AvailableSpace height);

void mason_node_compute_max_content(struct CMason *mason, struct CMasonNode *node);

void mason_node_compute_min_content(struct CMason *mason, struct CMasonNode *node);

void mason_node_compute(struct CMason *mason, struct CMasonNode *node);

struct CMasonNode *mason_node_get_child_at(struct CMason *mason,
                                           struct CMasonNode *node,
                                           uintptr_t index);

void mason_node_set_children(struct CMason *mason,
                             struct CMasonNode *node,
                             struct CMasonNode *const *children,
                             uintptr_t children_size);

void mason_node_add_children(struct CMason *mason,
                             struct CMasonNode *node,
                             struct CMasonNode *const *children,
                             uintptr_t children_size);

void mason_node_prepend_children(struct CMason *mason,
                                 struct CMasonNode *node,
                                 struct CMasonNode *const *children,
                                 uintptr_t children_size);

void mason_node_prepend(struct CMason *mason, struct CMasonNode *node, struct CMasonNode *child);

void mason_node_add_child(struct CMason *mason, struct CMasonNode *node, struct CMasonNode *child);

struct CMasonNode *mason_node_replace_child_at(struct CMason *mason,
                                               struct CMasonNode *node,
                                               struct CMasonNode *child,
                                               uintptr_t index);

void mason_node_add_child_at(struct CMason *mason,
                             struct CMasonNode *node,
                             struct CMasonNode *child,
                             uintptr_t index);

void mason_node_insert_child_before(struct CMason *mason,
                                    struct CMasonNode *node,
                                    struct CMasonNode *child,
                                    struct CMasonNode *reference);

void mason_node_insert_child_after(struct CMason *mason,
                                   struct CMasonNode *node,
                                   struct CMasonNode *child,
                                   struct CMasonNode *reference);

bool mason_node_dirty(struct CMason *mason, struct CMasonNode *node);

void mason_node_mark_dirty(struct CMason *mason, struct CMasonNode *node);

void mason_node_set_pseudo_states(struct CMason *mason, struct CMasonNode *node, uint16_t flags);

uint16_t mason_node_get_pseudo_states(struct CMason *mason, struct CMasonNode *node);

bool mason_node_has_pseudo_state(struct CMason *mason, struct CMasonNode *node, uint16_t flag);

/**
 * Return the node's state buffer as raw pointer + length.
 * The state buffer holds pseudo flags and other per-node state.
 */
const uint8_t *mason_node_get_state_buffer(struct CMason *mason,
                                           struct CMasonNode *node,
                                           uintptr_t *out_len);

/**
 * Return a mutable pointer to the node's state buffer.
 */
uint8_t *mason_node_get_state_buffer_mut(struct CMason *mason,
                                         struct CMasonNode *node,
                                         uintptr_t *out_len);

/**
 * Return an existing pseudo style buffer (read-only raw pointer + length).
 * Returns null if no pseudo buffer exists for the given flags.
 */
const uint8_t *mason_node_get_pseudo_style_buffer(struct CMason *mason,
                                                  struct CMasonNode *node,
                                                  uint16_t flags,
                                                  uintptr_t *out_len);

/**
 * Prepare (create if needed) and return a mutable pseudo style buffer.
 * Clones from the base style if this is the first call for the given pseudo state.
 * Returns a raw mutable pointer + length for direct buffer writes.
 */
uint8_t *mason_node_prepare_pseudo_style_buffer(struct CMason *mason,
                                                struct CMasonNode *node,
                                                uint16_t flags,
                                                uintptr_t *out_len);

bool mason_node_is_children_same(struct CMason *mason,
                                 struct CMasonNode *node,
                                 struct CMasonNode *const *children,
                                 uintptr_t children_size);

void mason_node_remove_children(struct CMason *mason, struct CMasonNode *node);

struct CMasonNode *mason_node_remove_child_at(struct CMason *mason,
                                              struct CMasonNode *node,
                                              uintptr_t index);

struct CMasonNode *mason_node_remove_child(struct CMason *mason,
                                           struct CMasonNode *node,
                                           struct CMasonNode *child);

struct NodeArray *mason_node_get_children(struct CMason *mason, struct CMasonNode *node);

#if !defined(TARGET_OS_ANDROID)
void mason_node_set_context(struct CMason *mason,
                            struct CMasonNode *node,
                            void *measure_data,
                            long long (*measure)(const void*, float, float, float, float));
#endif

#if !defined(TARGET_OS_ANDROID)
void mason_node_remove_context(struct CMason *mason, struct CMasonNode *node);
#endif

#if !defined(TARGET_OS_ANDROID)
void mason_node_set_apple_node(struct CMason *mason, struct CMasonNode *node, void *apple_node);
#endif

void mason_style_update_non_buffer_data(struct CMason *mason,
                                        struct CMasonNode *node,
                                        const char *grid_auto_rows,
                                        const char *grid_auto_columns,
                                        const char *grid_column,
                                        const char *grid_column_start,
                                        const char *grid_column_end,
                                        const char *grid_row,
                                        const char *grid_row_start,
                                        const char *grid_row_end,
                                        const char *grid_template_rows,
                                        const char *grid_template_columns,
                                        const char *grid_area,
                                        const char *grid_template_areas);

void mason_style_set_with_values(struct CMason *mason,
                                 struct CMasonNode *node,
                                 signed char display,
                                 signed char position,
                                 signed char direction,
                                 signed char flex_direction,
                                 signed char flex_wrap,
                                 signed char overflow,
                                 signed char align_items,
                                 signed char align_self,
                                 signed char align_content,
                                 signed char justify_items,
                                 signed char justify_self,
                                 signed char justify_content,
                                 signed char inset_left_type,
                                 float inset_left_value,
                                 signed char inset_right_type,
                                 float inset_right_value,
                                 signed char inset_top_type,
                                 float inset_top_value,
                                 signed char inset_bottom_type,
                                 float inset_bottom_value,
                                 signed char margin_left_type,
                                 float margin_left_value,
                                 signed char margin_right_type,
                                 float margin_right_value,
                                 signed char margin_top_type,
                                 float margin_top_value,
                                 signed char margin_bottom_type,
                                 float margin_bottom_value,
                                 signed char padding_left_type,
                                 float padding_left_value,
                                 signed char padding_right_type,
                                 float padding_right_value,
                                 signed char padding_top_type,
                                 float padding_top_value,
                                 signed char padding_bottom_type,
                                 float padding_bottom_value,
                                 signed char border_left_type,
                                 float border_left_value,
                                 signed char border_right_type,
                                 float border_right_value,
                                 signed char border_top_type,
                                 float border_top_value,
                                 signed char border_bottom_type,
                                 float border_bottom_value,
                                 float flex_grow,
                                 float flex_shrink,
                                 signed char flex_basis_type,
                                 float flex_basis_value,
                                 signed char width_type,
                                 float width_value,
                                 signed char height_type,
                                 float height_value,
                                 signed char min_width_type,
                                 float min_width_value,
                                 signed char min_height_type,
                                 float min_height_value,
                                 signed char max_width_type,
                                 float max_width_value,
                                 signed char max_height_type,
                                 float max_height_value,
                                 signed char gap_row_type,
                                 float gap_row_value,
                                 signed char gap_column_type,
                                 float gap_column_value,
                                 float aspect_ratio,
                                 const char *grid_auto_rows,
                                 const char *grid_auto_columns,
                                 signed char grid_auto_flow,
                                 const char *grid_column,
                                 const char *grid_column_start,
                                 const char *grid_column_end,
                                 const char *grid_row,
                                 const char *grid_row_start,
                                 const char *grid_row_end,
                                 const char *grid_template_rows,
                                 const char *grid_template_columns,
                                 signed char overflow_x,
                                 signed char overflow_y,
                                 float scrollbar_width,
                                 signed char text_align,
                                 signed char box_sizing,
                                 const char *grid_area,
                                 const char *grid_template_areas);

void mason_style_prepare_style_for_mut(struct CMason *mason, struct CMasonNode *node);

void mason_style_release_style_buffer(struct CMasonBuffer *buffer);

struct CMasonBuffer *mason_style_get_style_buffer(struct CMason *mason, struct CMasonNode *node);

void *mason_style_get_style_buffer_apple(struct CMason *mason, struct CMasonNode *node);

char *mason_style_get_grid_area_css(struct CMason *mason, struct CMasonNode *node);

char *mason_style_get_grid_template_areas_css(struct CMason *mason, struct CMasonNode *node);

char *mason_style_get_grid_auto_rows_css(struct CMason *mason, struct CMasonNode *node);

char *mason_style_get_grid_auto_columns_css(struct CMason *mason, struct CMasonNode *node);

char *mason_style_get_grid_column_css(struct CMason *mason, struct CMasonNode *node);

char *mason_style_get_grid_column_start_css(struct CMason *mason, struct CMasonNode *node);

char *mason_style_get_grid_column_end_css(struct CMason *mason, struct CMasonNode *node);

char *mason_style_get_grid_row_css(struct CMason *mason, struct CMasonNode *node);

char *mason_style_get_grid_row_start_css(struct CMason *mason, struct CMasonNode *node);

char *mason_style_get_grid_row_end_css(struct CMason *mason, struct CMasonNode *node);

char *mason_style_get_grid_template_rows_css(struct CMason *mason, struct CMasonNode *node);

char *mason_style_get_grid_template_columns_css(struct CMason *mason, struct CMasonNode *node);

struct CMasonMinMax mason_util_create_track_sizing_function_with_type_value(int32_t track_type,
                                                                            float track_value);

void mason_util_destroy_string(char *string);

#endif  /* MASON_C_H */
