#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.0.2 effective-5.10 (swiftlang-6.0.2.1.2 clang-1600.0.26.4)
#ifndef MASON_SWIFT_H
#define MASON_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="Mason",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)
typedef SWIFT_ENUM_NAMED(NSInteger, AlignContent, "AlignContent", open) {
  AlignContentNormal = -1,
  AlignContentStart = 0,
  AlignContentEnd = 1,
  AlignContentCenter = 2,
  AlignContentStretch = 3,
  AlignContentSpaceBetween = 4,
  AlignContentSpaceAround = 5,
  AlignContentSpaceEvenly = 6,
  AlignContentFlexStart = 7,
  AlignContentFlexEnd = 8,
};

typedef SWIFT_ENUM_NAMED(NSInteger, AlignItems, "AlignItems", open) {
  AlignItemsNormal = -1,
  AlignItemsStart = 0,
  AlignItemsEnd = 1,
  AlignItemsCenter = 2,
  AlignItemsBaseline = 3,
  AlignItemsStretch = 4,
  AlignItemsFlexStart = 5,
  AlignItemsFlexEnd = 6,
};

typedef SWIFT_ENUM_NAMED(NSInteger, AlignSelf, "AlignSelf", open) {
  AlignSelfNormal = -1,
  AlignSelfStart = 0,
  AlignSelfEnd = 1,
  AlignSelfCenter = 2,
  AlignSelfBaseline = 3,
  AlignSelfStretch = 4,
  AlignSelfFlexStart = 5,
  AlignSelfFlexEnd = 6,
};

typedef SWIFT_ENUM_NAMED(NSInteger, DecorationLine, "DecorationLine", open) {
  DecorationLineNone = 0,
  DecorationLineUnderline = 1,
  DecorationLineOverline = 2,
  DecorationLineLineThrough = 3,
};

typedef SWIFT_ENUM_NAMED(NSInteger, Direction, "Direction", open) {
  DirectionInherit = 0,
  DirectionLTR = 1,
  DirectionRTL = 2,
};

typedef SWIFT_ENUM_NAMED(NSInteger, Display, "Display", open) {
  DisplayNone = 0,
  DisplayFlex = 1,
  DisplayGrid = 2,
  DisplayBlock = 3,
};

typedef SWIFT_ENUM_NAMED(NSInteger, FlexDirection, "FlexDirection", open) {
  FlexDirectionRow = 0,
  FlexDirectionColumn = 1,
  FlexDirectionRowReverse = 2,
  FlexDirectionColumnReverse = 3,
};

typedef SWIFT_ENUM_NAMED(NSInteger, FlexWrap, "FlexWrap", open) {
  FlexWrapNoWrap = 0,
  FlexWrapWrap = 1,
  FlexWrapWrapReverse = 2,
};

typedef SWIFT_ENUM_NAMED(NSInteger, FontStyle, "FontStyle", open) {
  FontStyleNormal = 0,
  FontStyleItalic = 1,
  FontStyleOblique = 2,
};

typedef SWIFT_ENUM_NAMED(NSInteger, FlexGridAutoFlowWrap, "GridAutoFlow", open) {
  FlexGridAutoFlowWrapRow = 0,
  FlexGridAutoFlowWrapColumn = 1,
  FlexGridAutoFlowWrapRowDense = 2,
  FlexGridAutoFlowWrapColumnDense = 3,
};

enum GridPlacementCompatType : NSInteger;
@class NSString;

SWIFT_CLASS_NAMED("GridPlacementCompat")
@interface GridPlacementCompat : NSObject
- (nonnull instancetype)initWithSpan:(int16_t)span OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithLine:(int16_t)line OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) enum GridPlacementCompatType type;
@property (nonatomic, readonly) int16_t value;
@property (nonatomic, readonly, copy) NSString * _Nonnull cssValue;
@property (nonatomic, readonly, copy) NSString * _Nullable jsonValue;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) GridPlacementCompat * _Nonnull Auto;)
+ (GridPlacementCompat * _Nonnull)Auto SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM_NAMED(NSInteger, GridPlacementCompatType, "GridPlacementCompatType", open) {
  GridPlacementCompatTypeAuto = 0,
  GridPlacementCompatTypeLine = 1,
  GridPlacementCompatTypeSpan = 2,
};


SWIFT_CLASS_NAMED("GridTrackRepetition")
@interface GridTrackRepetition : NSObject
@property (nonatomic, readonly) int32_t type;
@property (nonatomic, readonly) uint16_t value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) GridTrackRepetition * _Nonnull AutoFill;)
+ (GridTrackRepetition * _Nonnull)AutoFill SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) GridTrackRepetition * _Nonnull AutoFit;)
+ (GridTrackRepetition * _Nonnull)AutoFit SWIFT_WARN_UNUSED_RESULT;
+ (GridTrackRepetition * _Nonnull)Count:(uint16_t)value SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM_NAMED(NSInteger, JustifyContent, "JustifyContent", open) {
  JustifyContentNormal = -1,
  JustifyContentStart = 0,
  JustifyContentEnd = 1,
  JustifyContentCenter = 2,
  JustifyContentStretch = 3,
  JustifyContentSpaceBetween = 4,
  JustifyContentSpaceAround = 5,
  JustifyContentSpaceEvenly = 6,
  JustifyContentFlexStart = 7,
  JustifyContentFlexEnd = 8,
};

typedef SWIFT_ENUM_NAMED(NSInteger, JustifyItems, "JustifyItems", open) {
  JustifyItemsNormal = -1,
  JustifyItemsStart = 0,
  JustifyItemsEnd = 1,
  JustifyItemsCenter = 2,
  JustifyItemsBaseline = 3,
  JustifyItemsStretch = 4,
  JustifyItemsFlexStart = 5,
  JustifyItemsFlexEnd = 6,
};

typedef SWIFT_ENUM_NAMED(NSInteger, JustifySelf, "JustifySelf", open) {
  JustifySelfNormal = -1,
  JustifySelfStart = 0,
  JustifySelfEnd = 1,
  JustifySelfCenter = 2,
  JustifySelfBaseline = 3,
  JustifySelfStretch = 4,
  JustifySelfFlexStart = 5,
  JustifySelfFlexEnd = 6,
};


SWIFT_CLASS_NAMED("LineGridPlacementCompat")
@interface LineGridPlacementCompat : NSObject
@property (nonatomic, readonly, strong) GridPlacementCompat * _Nonnull start;
@property (nonatomic, readonly, strong) GridPlacementCompat * _Nonnull end;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM_NAMED(NSInteger, MasonBoxSizing, "MasonBoxSizing", open) {
  MasonBoxSizingBorderBox = 0,
  MasonBoxSizingContentBox = 1,
};

enum MasonDimensionCompatType : NSInteger;

SWIFT_CLASS_NAMED("MasonDimensionCompat")
@interface MasonDimensionCompat : NSObject
- (nonnull instancetype)initWithPoints:(float)points OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithPercent:(float)percent OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) enum MasonDimensionCompatType type;
@property (nonatomic, readonly) float value;
@property (nonatomic, readonly, copy) NSString * _Nonnull cssValue;
@property (nonatomic, readonly, copy) NSString * _Nullable jsonValue;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) MasonDimensionCompat * _Nonnull Auto;)
+ (MasonDimensionCompat * _Nonnull)Auto SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) MasonDimensionCompat * _Nonnull Zero;)
+ (MasonDimensionCompat * _Nonnull)Zero SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM_NAMED(NSInteger, MasonDimensionCompatType, "MasonDimensionCompatType", open) {
  MasonDimensionCompatTypeAuto = 0,
  MasonDimensionCompatTypePoints = 1,
  MasonDimensionCompatTypePercent = 2,
};


SWIFT_CLASS_NAMED("MasonDimensionRectCompat")
@interface MasonDimensionRectCompat : NSObject
@property (nonatomic, strong) MasonDimensionCompat * _Nonnull left;
@property (nonatomic, strong) MasonDimensionCompat * _Nonnull right;
@property (nonatomic, strong) MasonDimensionCompat * _Nonnull top;
@property (nonatomic, strong) MasonDimensionCompat * _Nonnull bottom;
- (nonnull instancetype)init:(MasonDimensionCompat * _Nonnull)left :(MasonDimensionCompat * _Nonnull)right :(MasonDimensionCompat * _Nonnull)top :(MasonDimensionCompat * _Nonnull)bottom OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("MasonDimensionSizeCompat")
@interface MasonDimensionSizeCompat : NSObject
@property (nonatomic, strong) MasonDimensionCompat * _Nonnull width;
@property (nonatomic, strong) MasonDimensionCompat * _Nonnull height;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("MasonLayout")
@interface MasonLayout : NSObject
@property (nonatomic, readonly) NSInteger order;
@property (nonatomic, readonly) float x;
@property (nonatomic, readonly) float y;
@property (nonatomic, readonly) float width;
@property (nonatomic, readonly) float height;
@property (nonatomic, readonly, copy) NSArray<MasonLayout *> * _Nonnull children;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

enum MasonLengthPercentageAutoCompatType : NSInteger;

SWIFT_CLASS_NAMED("MasonLengthPercentageAutoCompat")
@interface MasonLengthPercentageAutoCompat : NSObject
- (nonnull instancetype)initWithPoints:(float)points OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithPercent:(float)percent OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) enum MasonLengthPercentageAutoCompatType type;
@property (nonatomic, readonly) float value;
@property (nonatomic, readonly, copy) NSString * _Nonnull cssValue;
@property (nonatomic, readonly, copy) NSString * _Nullable jsonValue;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) MasonLengthPercentageAutoCompat * _Nonnull Auto;)
+ (MasonLengthPercentageAutoCompat * _Nonnull)Auto SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) MasonLengthPercentageAutoCompat * _Nonnull Zero;)
+ (MasonLengthPercentageAutoCompat * _Nonnull)Zero SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM_NAMED(NSInteger, MasonLengthPercentageAutoCompatType, "MasonLengthPercentageAutoCompatType", open) {
  MasonLengthPercentageAutoCompatTypeAuto = 0,
  MasonLengthPercentageAutoCompatTypePoints = 1,
  MasonLengthPercentageAutoCompatTypePercent = 2,
};


SWIFT_CLASS_NAMED("MasonLengthPercentageAutoRectCompat")
@interface MasonLengthPercentageAutoRectCompat : NSObject
@property (nonatomic, strong) MasonLengthPercentageAutoCompat * _Nonnull left;
@property (nonatomic, strong) MasonLengthPercentageAutoCompat * _Nonnull right;
@property (nonatomic, strong) MasonLengthPercentageAutoCompat * _Nonnull top;
@property (nonatomic, strong) MasonLengthPercentageAutoCompat * _Nonnull bottom;
- (nonnull instancetype)init:(MasonLengthPercentageAutoCompat * _Nonnull)left :(MasonLengthPercentageAutoCompat * _Nonnull)right :(MasonLengthPercentageAutoCompat * _Nonnull)top :(MasonLengthPercentageAutoCompat * _Nonnull)bottom OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("MasonLengthPercentageAutoSizeCompat")
@interface MasonLengthPercentageAutoSizeCompat : NSObject
@property (nonatomic, strong) MasonLengthPercentageAutoCompat * _Nonnull width;
@property (nonatomic, strong) MasonLengthPercentageAutoCompat * _Nonnull height;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

enum MasonLengthPercentageCompatType : NSInteger;

SWIFT_CLASS_NAMED("MasonLengthPercentageCompat")
@interface MasonLengthPercentageCompat : NSObject
- (nonnull instancetype)initWithPoints:(float)points OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithPercent:(float)percent OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) enum MasonLengthPercentageCompatType type;
@property (nonatomic, readonly) float value;
@property (nonatomic, readonly, copy) NSString * _Nonnull cssValue;
@property (nonatomic, readonly, copy) NSString * _Nullable jsonValue;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) MasonLengthPercentageCompat * _Nonnull Zero;)
+ (MasonLengthPercentageCompat * _Nonnull)Zero SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM_NAMED(NSInteger, MasonLengthPercentageCompatType, "MasonLengthPercentageCompatType", open) {
  MasonLengthPercentageCompatTypePoints = 0,
  MasonLengthPercentageCompatTypePercent = 1,
};


SWIFT_CLASS_NAMED("MasonLengthPercentageRectCompat")
@interface MasonLengthPercentageRectCompat : NSObject
@property (nonatomic, strong) MasonLengthPercentageCompat * _Nonnull left;
@property (nonatomic, strong) MasonLengthPercentageCompat * _Nonnull right;
@property (nonatomic, strong) MasonLengthPercentageCompat * _Nonnull top;
@property (nonatomic, strong) MasonLengthPercentageCompat * _Nonnull bottom;
- (nonnull instancetype)init:(MasonLengthPercentageCompat * _Nonnull)left :(MasonLengthPercentageCompat * _Nonnull)right :(MasonLengthPercentageCompat * _Nonnull)top :(MasonLengthPercentageCompat * _Nonnull)bottom OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("MasonLengthPercentageSizeCompat")
@interface MasonLengthPercentageSizeCompat : NSObject
@property (nonatomic, strong) MasonLengthPercentageCompat * _Nonnull width;
@property (nonatomic, strong) MasonLengthPercentageCompat * _Nonnull height;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class MasonStyle;
@class NSCMason;

SWIFT_CLASS_NAMED("MasonNode")
@interface MasonNode : NSObject
@property (nonatomic, readonly) void * _Nullable nativePtr;
@property (nonatomic, readonly, strong) MasonLayout * _Nullable layoutCache;
@property (nonatomic) id _Nullable data;
@property (nonatomic, strong) MasonStyle * _Nonnull style;
@property (nonatomic, readonly, strong) MasonNode * _Nullable owner;
@property (nonatomic, readonly, copy) NSArray<MasonNode *> * _Nonnull children;
- (nonnull instancetype)initWithMason:(NSCMason * _Nonnull)doc children:(NSArray<MasonNode *> * _Nonnull)nodes OBJC_DESIGNATED_INITIALIZER;
- (MasonLayout * _Nonnull)layout;
@property (nonatomic, readonly) BOOL isDirty;
- (void)markDirty;
- (MasonNode * _Nullable)getRoot SWIFT_WARN_UNUSED_RESULT;
- (void)compute;
- (void)compute:(float)width :(float)height;
- (void)computeMaxContent;
- (void)computeMinContent;
- (void)computeWithSize:(float)width :(float)height;
- (void)computeWithViewSize;
- (void)computeWithViewSizeWithLayout:(BOOL)layout;
- (void)computeWithMaxContent;
- (void)computeWithMinContent;
- (void)attachAndApply;
- (void)setChildrenWithValue:(NSArray<MasonNode *> * _Nonnull)value;
- (void)addChildren:(NSArray<MasonNode *> * _Nonnull)children;
- (void)configure:(SWIFT_NOESCAPE void (^ _Nonnull)(MasonNode * _Nonnull))block;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSMutableData;
@class NSData;
enum Position : NSInteger;
enum Overflow : NSInteger;
enum MasonTextAlign : NSInteger;
@class MinMax;
@class TrackSizingFunction;

SWIFT_CLASS_NAMED("MasonStyle")
@interface MasonStyle : NSObject
@property (nonatomic, strong) NSMutableData * _Nonnull valuesCompat;
@property (nonatomic, copy) NSData * _Nonnull values;
- (nonnull instancetype)initWithNode:(MasonNode * _Nonnull)node OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic) enum Display display;
@property (nonatomic) enum Position position;
@property (nonatomic) enum Direction direction;
@property (nonatomic) enum FlexDirection flexDirection;
@property (nonatomic) enum FlexWrap flexWrap;
@property (nonatomic) enum Overflow overflowX;
@property (nonatomic) enum Overflow overflowY;
@property (nonatomic) enum AlignItems alignItems;
@property (nonatomic) enum AlignSelf alignSelf;
@property (nonatomic) enum AlignContent alignContent;
@property (nonatomic) enum JustifyItems justifyItems;
@property (nonatomic) enum JustifySelf justifySelf;
@property (nonatomic) enum JustifyContent justifyContent;
@property (nonatomic, strong) MasonLengthPercentageAutoRectCompat * _Nonnull insetCompat;
- (void)setInsetLeft:(float)value :(NSInteger)type;
- (void)setInsetRight:(float)value :(NSInteger)type;
- (void)setInsetTop:(float)value :(NSInteger)type;
- (void)setInsetBottom:(float)value :(NSInteger)type;
- (void)setInsetWithValueType:(float)value :(NSInteger)type;
@property (nonatomic, strong) MasonLengthPercentageAutoRectCompat * _Nonnull marginCompat;
- (void)setMarginLeft:(float)value :(NSInteger)type;
- (void)setMarginRight:(float)value :(NSInteger)type;
- (void)setMarginTop:(float)value :(NSInteger)type;
- (void)setMarginBottom:(float)value :(NSInteger)type;
- (void)setMarginWithValueType:(float)value :(NSInteger)type;
@property (nonatomic, strong) MasonLengthPercentageRectCompat * _Nonnull paddingCompat;
- (void)setPaddingLeft:(float)value :(NSInteger)type;
- (void)setPaddingRight:(float)value :(NSInteger)type;
- (void)setPaddingTop:(float)value :(NSInteger)type;
- (void)setPaddingBottom:(float)value :(NSInteger)type;
- (void)setPaddingWithValueType:(float)value :(NSInteger)type;
@property (nonatomic, strong) MasonLengthPercentageRectCompat * _Nonnull borderCompat;
- (void)setBorderLeft:(float)value :(NSInteger)type;
- (void)setBorderRight:(float)value :(NSInteger)type;
- (void)setBorderTop:(float)value :(NSInteger)type;
- (void)setBorderBottom:(float)value :(NSInteger)type;
- (void)setBorderWithValueType:(float)value :(NSInteger)type;
@property (nonatomic) float flexGrow;
@property (nonatomic) float flexShrink;
- (void)setFlexBasis:(float)value :(NSInteger)type;
- (void)setScrollBarWidth:(float)value;
@property (nonatomic) enum MasonTextAlign textAlign;
@property (nonatomic) enum MasonBoxSizing boxSizing;
@property (nonatomic, strong) MasonDimensionSizeCompat * _Nonnull minSizeCompat;
- (void)setMinSizeWidth:(float)value :(NSInteger)type;
- (void)setMinSizeHeight:(float)value :(NSInteger)type;
- (void)setMinSizeWidthHeight:(float)value :(NSInteger)type;
@property (nonatomic, strong) MasonDimensionSizeCompat * _Nonnull sizeCompat;
@property (nonatomic, strong) MasonDimensionCompat * _Nonnull sizeCompatWidth;
@property (nonatomic, strong) MasonDimensionCompat * _Nonnull sizeCompatHeight;
- (void)setSizeWidth:(float)value :(NSInteger)type;
- (void)setSizeHeight:(float)value :(NSInteger)type;
- (void)setSizeWidthHeight:(float)value :(NSInteger)type;
@property (nonatomic, strong) MasonDimensionSizeCompat * _Nonnull maxSizeCompat;
- (void)setMaxSizeWidth:(float)value :(NSInteger)type;
- (void)setMaxSizeHeight:(float)value :(NSInteger)type;
- (void)setMaxSizeWidthHeight:(float)value :(NSInteger)type;
@property (nonatomic, strong) MasonLengthPercentageSizeCompat * _Nonnull gapCompat;
- (void)setGapRow:(float)value :(NSInteger)type;
- (void)setGapColumn:(float)value :(NSInteger)type;
- (void)setRowGap:(float)value :(NSInteger)type;
- (void)setColumnGap:(float)value :(NSInteger)type;
@property (nonatomic, copy) NSArray<MinMax *> * _Nonnull gridAutoRows;
@property (nonatomic, copy) NSArray<MinMax *> * _Nonnull gridAutoColumns;
@property (nonatomic) enum FlexGridAutoFlowWrap gridAutoFlow;
@property (nonatomic, strong) LineGridPlacementCompat * _Nonnull gridColumnCompat;
@property (nonatomic, strong) GridPlacementCompat * _Nonnull gridColumnStartCompat;
@property (nonatomic, strong) GridPlacementCompat * _Nonnull gridColumnEndCompat;
@property (nonatomic, strong) LineGridPlacementCompat * _Nonnull gridRowCompat;
@property (nonatomic, strong) GridPlacementCompat * _Nonnull gridRowStartCompat;
@property (nonatomic, strong) GridPlacementCompat * _Nonnull gridRowEndCompat;
@property (nonatomic, copy) NSArray<TrackSizingFunction *> * _Nonnull gridTemplateRows;
@property (nonatomic, copy) NSArray<TrackSizingFunction *> * _Nonnull gridTemplateColumns;
- (void)updateNativeStyle;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSCoder;
@class NSMutableAttributedString;
@class UIFont;
enum TextTransform : NSInteger;
@class UIColor;
enum TextWrap : NSInteger;

SWIFT_CLASS_NAMED("MasonText")
@interface MasonText : UIView
@property (nonatomic, readonly, strong) MasonText * _Nullable owner;
@property (nonatomic, readonly, strong) MasonNode * _Nonnull node;
@property (nonatomic, readonly, copy) NSData * _Nonnull textValues;
- (nonnull instancetype)initWithMason:(NSCMason * _Nonnull)mason OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNode:(MasonNode * _Nonnull)masonNode OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
@property (nonatomic, readonly, strong) UIView * _Nonnull uiView;
@property (nonatomic, readonly, strong) MasonStyle * _Nonnull style;
- (void)markNodeDirty;
- (BOOL)isNodeDirty SWIFT_WARN_UNUSED_RESULT;
- (void)configure:(SWIFT_NOESCAPE void (^ _Nonnull)(MasonNode * _Nonnull))block;
- (void)updateText:(NSString * _Nullable)value;
@property (nonatomic, strong) NSMutableAttributedString * _Nonnull txtToRender;
@property (nonatomic, readonly, strong) UIFont * _Nonnull font;
- (void)invalidateStyle:(int64_t)state;
@property (nonatomic) enum TextTransform textTransform;
@property (nonatomic) CGFloat fontSize;
@property (nonatomic) enum FontStyle fontStyle;
- (void)setFontStyle:(enum FontStyle)style slant:(int32_t)slant;
@property (nonatomic, copy) NSString * _Nonnull fontWeight;
@property (nonatomic) uint32_t color;
@property (nonatomic) uint32_t backgroundColorValue;
- (void)setColorWithUi:(UIColor * _Nonnull)color;
- (void)setBackgroundColorWithUi:(UIColor * _Nonnull)color;
- (void)setDecorationColorWithUi:(UIColor * _Nonnull)color;
@property (nonatomic) uint32_t decorationColor;
@property (nonatomic) enum DecorationLine decorationLine;
@property (nonatomic) enum TextWrap textWrap;
- (void)drawRect:(CGRect)rect;
- (void)addView:(UIView * _Nonnull)view :(NSInteger)index;
- (void)removeView:(UIView * _Nonnull)view;
@property (nonatomic, copy) NSString * _Nullable text;
- (void)syncStyle:(NSString * _Nonnull)state :(NSString * _Nonnull)textState;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end

typedef SWIFT_ENUM_NAMED(NSInteger, MasonTextAlign, "MasonTextAlign", open) {
  MasonTextAlignAuto = 0,
  MasonTextAlignLeft = 1,
  MasonTextAlignRight = 2,
  MasonTextAlignCenter = 3,
  MasonTextAlignJustify = 4,
  MasonTextAlignStart = 5,
  MasonTextAlignEnd = 6,
};


SWIFT_CLASS_NAMED("MasonUIView")
@interface MasonUIView : UIView
@property (nonatomic, readonly, strong) UIView * _Nonnull uiView;
- (void)markNodeDirty;
- (BOOL)isNodeDirty SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, strong) MasonNode * _Nonnull node;
@property (nonatomic, readonly, strong) NSCMason * _Nonnull mason;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
+ (MasonUIView * _Nonnull)createGridView:(NSCMason * _Nonnull)mason SWIFT_WARN_UNUSED_RESULT;
+ (MasonUIView * _Nonnull)createFlexView:(NSCMason * _Nonnull)mason SWIFT_WARN_UNUSED_RESULT;
+ (MasonUIView * _Nonnull)createBlockView:(NSCMason * _Nonnull)mason SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly) int64_t masonPtr;
@property (nonatomic, readonly) int64_t masonNodePtr;
@property (nonatomic, readonly, copy) NSString * _Nonnull masonPtrs;
@property (nonatomic, strong) MasonStyle * _Nonnull style;
- (void)addView:(UIView * _Nonnull)view;
- (void)addView:(UIView * _Nonnull)view at:(NSInteger)at;
- (void)syncStyle:(NSString * _Nonnull)state;
- (void)addSubviews:(NSArray<UIView *> * _Nonnull)views;
- (void)addSubviews:(NSArray<UIView *> * _Nonnull)views at:(NSInteger)index;
- (void)configure:(SWIFT_NOESCAPE void (^ _Nonnull)(MasonNode * _Nonnull))block;
@property (nonatomic) BOOL inBatch;
@property (nonatomic) enum Display display;
@property (nonatomic) enum Position _position;
@property (nonatomic) enum Direction direction;
@property (nonatomic) enum FlexDirection flexDirection;
@property (nonatomic) enum FlexWrap flexWrap;
@property (nonatomic) enum Overflow overflowX;
@property (nonatomic) enum Overflow overflowY;
@property (nonatomic) enum AlignItems alignItems;
@property (nonatomic) enum AlignSelf alignSelf;
@property (nonatomic) enum AlignContent alignContent;
@property (nonatomic) enum JustifyItems justifyItems;
@property (nonatomic) enum JustifySelf justifySelf;
@property (nonatomic) enum JustifyContent justifyContent;
@property (nonatomic) float flexGrow;
@property (nonatomic) float flexShrink;
@property (nonatomic, strong) MasonDimensionCompat * _Nonnull scrollBarWidthCompat;
@property (nonatomic, strong) MasonDimensionCompat * _Nonnull flexBasisCompat;
@property (nonatomic) float aspectRatio;
@property (nonatomic, copy) NSArray<MinMax *> * _Nonnull gridAutoRows;
@property (nonatomic, copy) NSArray<MinMax *> * _Nonnull gridAutoColumns;
@property (nonatomic) enum FlexGridAutoFlowWrap gridAutoFlow;
@property (nonatomic, strong) LineGridPlacementCompat * _Nonnull gridColumnCompat;
@property (nonatomic, strong) GridPlacementCompat * _Nonnull gridColumnStartCompat;
@property (nonatomic, strong) GridPlacementCompat * _Nonnull gridColumnEndCompat;
@property (nonatomic, strong) LineGridPlacementCompat * _Nonnull gridRowCompat;
@property (nonatomic, strong) GridPlacementCompat * _Nonnull gridRowStartCompat;
@property (nonatomic, strong) GridPlacementCompat * _Nonnull gridRowEndCompat;
@property (nonatomic, copy) NSArray<TrackSizingFunction *> * _Nonnull gridTemplateRows;
@property (nonatomic, copy) NSArray<TrackSizingFunction *> * _Nonnull gridTemplateColumns;
- (void)setPadding:(float)left :(float)right :(float)top :(float)bottom;
- (MasonLengthPercentageRectCompat * _Nonnull)getPadding SWIFT_WARN_UNUSED_RESULT;
- (void)setPaddingLeft:(float)left :(NSInteger)type;
- (void)setPaddingRight:(float)right :(NSInteger)type;
- (void)setPaddingTop:(float)top :(NSInteger)type;
- (void)setPaddingBottom:(float)bottom :(NSInteger)type;
- (MasonLengthPercentageCompat * _Nonnull)getPaddingLeft SWIFT_WARN_UNUSED_RESULT;
- (MasonLengthPercentageCompat * _Nonnull)getPaddingRight SWIFT_WARN_UNUSED_RESULT;
- (MasonLengthPercentageCompat * _Nonnull)getPaddingTop SWIFT_WARN_UNUSED_RESULT;
- (MasonLengthPercentageCompat * _Nonnull)getPaddingBottom SWIFT_WARN_UNUSED_RESULT;
- (void)setBorder:(float)left :(float)top :(float)right :(float)bottom;
- (MasonLengthPercentageRectCompat * _Nonnull)getBorder SWIFT_WARN_UNUSED_RESULT;
- (void)setBorderLeft:(float)left :(NSInteger)type;
- (void)setBorderRight:(float)right :(NSInteger)type;
- (void)setBorderTop:(float)top :(NSInteger)type;
- (void)setBorderBottom:(float)bottom :(NSInteger)type;
- (MasonLengthPercentageCompat * _Nonnull)getBorderLeft SWIFT_WARN_UNUSED_RESULT;
- (MasonLengthPercentageCompat * _Nonnull)getBorderRight SWIFT_WARN_UNUSED_RESULT;
- (MasonLengthPercentageCompat * _Nonnull)getBorderBottom SWIFT_WARN_UNUSED_RESULT;
- (MasonLengthPercentageCompat * _Nonnull)getBorderTop SWIFT_WARN_UNUSED_RESULT;
- (void)setMargin:(float)left :(float)top :(float)right :(float)bottom;
- (MasonLengthPercentageAutoRectCompat * _Nonnull)getMargin SWIFT_WARN_UNUSED_RESULT;
- (void)setMarginLeft:(float)left :(NSInteger)type;
- (void)setMarginRight:(float)right :(NSInteger)type;
- (void)setMarginTop:(float)top :(NSInteger)type;
- (void)setMarginBottom:(float)bottom :(NSInteger)type;
- (MasonLengthPercentageAutoCompat * _Nonnull)getMarginLeft SWIFT_WARN_UNUSED_RESULT;
- (MasonLengthPercentageAutoCompat * _Nonnull)getMarginRight SWIFT_WARN_UNUSED_RESULT;
- (MasonLengthPercentageAutoCompat * _Nonnull)getMarginTop SWIFT_WARN_UNUSED_RESULT;
- (MasonLengthPercentageAutoCompat * _Nonnull)getMarginBottom SWIFT_WARN_UNUSED_RESULT;
- (void)setInset:(float)left :(float)top :(float)right :(float)bottom;
- (MasonLengthPercentageAutoRectCompat * _Nonnull)getInset SWIFT_WARN_UNUSED_RESULT;
- (void)setInsetLeft:(float)left :(NSInteger)type;
- (void)setInsetRight:(float)right :(NSInteger)type;
- (void)setInsetTop:(float)top :(NSInteger)type;
- (void)setInsetBottom:(float)bottom :(NSInteger)type;
- (MasonLengthPercentageAutoCompat * _Nonnull)getInsetLeft SWIFT_WARN_UNUSED_RESULT;
- (MasonLengthPercentageAutoCompat * _Nonnull)getInsetRight SWIFT_WARN_UNUSED_RESULT;
- (MasonLengthPercentageAutoCompat * _Nonnull)getInsetTop SWIFT_WARN_UNUSED_RESULT;
- (MasonLengthPercentageAutoCompat * _Nonnull)getInsetBottom SWIFT_WARN_UNUSED_RESULT;
- (void)setMinSize:(float)width :(float)height;
- (MasonDimensionSizeCompat * _Nonnull)getMinSize SWIFT_WARN_UNUSED_RESULT;
- (void)setMinSizeWidth:(float)width :(NSInteger)type;
- (void)setMinSizeHeight:(float)height :(NSInteger)type;
- (MasonDimensionCompat * _Nonnull)getMinSizeWidth SWIFT_WARN_UNUSED_RESULT;
- (MasonDimensionCompat * _Nonnull)getMinSizeHeight SWIFT_WARN_UNUSED_RESULT;
- (void)setSize:(float)width :(float)height;
- (void)setSizeWidth:(float)width :(NSInteger)type;
- (void)setSizeHeight:(float)height :(NSInteger)type;
- (MasonDimensionSizeCompat * _Nonnull)getSize SWIFT_WARN_UNUSED_RESULT;
- (MasonDimensionCompat * _Nonnull)getSizeWidth SWIFT_WARN_UNUSED_RESULT;
- (MasonDimensionCompat * _Nonnull)getSizeHeight SWIFT_WARN_UNUSED_RESULT;
- (void)setMaxSize:(float)width :(float)height;
- (MasonDimensionSizeCompat * _Nonnull)getMaxSize SWIFT_WARN_UNUSED_RESULT;
- (void)setMaxSizeWidth:(float)width :(NSInteger)type;
- (void)setMaxSizeHeight:(float)height :(NSInteger)type;
- (MasonDimensionCompat * _Nonnull)getMaxSizeWidth SWIFT_WARN_UNUSED_RESULT;
- (MasonDimensionCompat * _Nonnull)getMaxSizeHeight SWIFT_WARN_UNUSED_RESULT;
- (void)setGap:(float)width :(float)height;
- (void)setGapWithWidthHeightType:(float)width :(NSInteger)width_type :(float)height :(NSInteger)height_type;
- (MasonLengthPercentageSizeCompat * _Nonnull)getGap SWIFT_WARN_UNUSED_RESULT;
- (void)setRowGap:(float)row :(NSInteger)type;
- (void)setColumnGap:(float)column :(NSInteger)type;
- (MasonLengthPercentageCompat * _Nonnull)getRowGap SWIFT_WARN_UNUSED_RESULT;
- (MasonLengthPercentageCompat * _Nonnull)getColumnGap SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS_NAMED("MaxSizing")
@interface MaxSizing : NSObject
@property (nonatomic, readonly) float value;
+ (MaxSizing * _Nonnull)Points:(float)points SWIFT_WARN_UNUSED_RESULT;
+ (MaxSizing * _Nonnull)Percent:(float)percent SWIFT_WARN_UNUSED_RESULT;
+ (MaxSizing * _Nonnull)FitContent:(float)fit SWIFT_WARN_UNUSED_RESULT;
+ (MaxSizing * _Nonnull)FitContentPercent:(float)fit SWIFT_WARN_UNUSED_RESULT;
+ (MaxSizing * _Nonnull)Fraction:(float)flex SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) MaxSizing * _Nonnull Auto;)
+ (MaxSizing * _Nonnull)Auto SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) MaxSizing * _Nonnull MinContent;)
+ (MaxSizing * _Nonnull)MinContent SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) MaxSizing * _Nonnull MaxContent;)
+ (MaxSizing * _Nonnull)MaxContent SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, copy) NSString * _Nonnull cssValue;
@property (nonatomic, readonly, copy) NSString * _Nullable jsonValue;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("MeasureOutput")
@interface MeasureOutput : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class MinSizing;

SWIFT_CLASS_NAMED("MinMax")
@interface MinMax : NSObject
- (nonnull instancetype)init:(MinSizing * _Nonnull)min :(MaxSizing * _Nonnull)max OBJC_DESIGNATED_INITIALIZER;
+ (MinMax * _Nonnull)PointsWithPoints:(float)points SWIFT_WARN_UNUSED_RESULT;
+ (MinMax * _Nonnull)PercentWithPercent:(float)percent SWIFT_WARN_UNUSED_RESULT;
+ (MinMax * _Nonnull)FlexWithFlex:(float)flex SWIFT_WARN_UNUSED_RESULT;
+ (MinMax * _Nonnull)FitContentWithFit:(float)fit SWIFT_WARN_UNUSED_RESULT;
+ (MinMax * _Nonnull)FitContentPercentWithFit:(float)fit SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) MinMax * _Nonnull Auto;)
+ (MinMax * _Nonnull)Auto SWIFT_WARN_UNUSED_RESULT;
+ (MinMax * _Nullable)fromTypeValue:(NSInteger)minType :(float)minValue :(NSInteger)maxType :(float)maxValue SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, copy) NSString * _Nonnull cssValue;
@property (nonatomic, readonly, copy) NSString * _Nullable jsonValue;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("MinSizing")
@interface MinSizing : NSObject
@property (nonatomic, readonly) float value;
+ (MinSizing * _Nonnull)Points:(float)points SWIFT_WARN_UNUSED_RESULT;
+ (MinSizing * _Nonnull)Percent:(float)percent SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) MinSizing * _Nonnull Auto;)
+ (MinSizing * _Nonnull)Auto SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) MinSizing * _Nonnull MinContent;)
+ (MinSizing * _Nonnull)MinContent SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) MinSizing * _Nonnull MaxContent;)
+ (MinSizing * _Nonnull)MaxContent SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, copy) NSString * _Nonnull cssValue;
@property (nonatomic, readonly, copy) NSString * _Nullable jsonValue;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("NSCMason")
@interface NSCMason : NSObject
@property (nonatomic, readonly) void * _Nullable nativePtr;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) NSCMason * _Nonnull shared;)
+ (NSCMason * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
+ (void)setShared:(NSCMason * _Nonnull)value;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (MasonNode * _Nonnull)nodeForView:(UIView * _Nonnull)view :(BOOL)isLeaf SWIFT_WARN_UNUSED_RESULT;
- (void)clear;
- (MasonUIView * _Nonnull)createView SWIFT_WARN_UNUSED_RESULT;
- (MasonText * _Nonnull)createTextView SWIFT_WARN_UNUSED_RESULT;
- (MasonNode * _Nonnull)createNode SWIFT_WARN_UNUSED_RESULT;
- (void)printTree:(MasonNode * _Nonnull)node;
- (MasonNode * _Nonnull)createTextNode SWIFT_WARN_UNUSED_RESULT;
@end

typedef SWIFT_ENUM_NAMED(NSInteger, Overflow, "Overflow", open) {
  OverflowUnset = 0,
  OverflowVisible = 1,
  OverflowHidden = 2,
  OverflowScroll = 3,
};

typedef SWIFT_ENUM_NAMED(NSInteger, Position, "Position", open) {
  PositionRelative = 0,
  PositionAbsolute = 1,
};

typedef SWIFT_ENUM_NAMED(NSInteger, TextTransform, "TextTransform", open) {
  TextTransformNone = 0,
  TextTransformCapitalize = 1,
  TextTransformUppercase = 2,
  TextTransformLowercase = 3,
  TextTransformFullWidth = 4,
  TextTransformFullSizeKana = 5,
  TextTransformMathAuto = 6,
};

typedef SWIFT_ENUM_NAMED(NSInteger, TextWrap, "TextWrap", open) {
  TextWrapNoWrap = 0,
  TextWrapWrap = 1,
  TextWrapBalance = 2,
};


SWIFT_CLASS_NAMED("TrackSizingFunction")
@interface TrackSizingFunction : NSObject
@property (nonatomic, readonly) BOOL isRepeating;
@property (nonatomic, readonly) id _Nullable value;
+ (TrackSizingFunction * _Nonnull)Single:(MinMax * _Nonnull)value SWIFT_WARN_UNUSED_RESULT;
+ (TrackSizingFunction * _Nonnull)AutoRepeat:(GridTrackRepetition * _Nonnull)gridTrackRepetition :(NSArray<MinMax *> * _Nonnull)value SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 6.0.2 effective-5.10 (swiftlang-6.0.2.1.2 clang-1600.0.26.4)
#ifndef MASON_SWIFT_H
#define MASON_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="Mason",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)
typedef SWIFT_ENUM_NAMED(NSInteger, AlignContent, "AlignContent", open) {
  AlignContentNormal = -1,
  AlignContentStart = 0,
  AlignContentEnd = 1,
  AlignContentCenter = 2,
  AlignContentStretch = 3,
  AlignContentSpaceBetween = 4,
  AlignContentSpaceAround = 5,
  AlignContentSpaceEvenly = 6,
  AlignContentFlexStart = 7,
  AlignContentFlexEnd = 8,
};

typedef SWIFT_ENUM_NAMED(NSInteger, AlignItems, "AlignItems", open) {
  AlignItemsNormal = -1,
  AlignItemsStart = 0,
  AlignItemsEnd = 1,
  AlignItemsCenter = 2,
  AlignItemsBaseline = 3,
  AlignItemsStretch = 4,
  AlignItemsFlexStart = 5,
  AlignItemsFlexEnd = 6,
};

typedef SWIFT_ENUM_NAMED(NSInteger, AlignSelf, "AlignSelf", open) {
  AlignSelfNormal = -1,
  AlignSelfStart = 0,
  AlignSelfEnd = 1,
  AlignSelfCenter = 2,
  AlignSelfBaseline = 3,
  AlignSelfStretch = 4,
  AlignSelfFlexStart = 5,
  AlignSelfFlexEnd = 6,
};

typedef SWIFT_ENUM_NAMED(NSInteger, DecorationLine, "DecorationLine", open) {
  DecorationLineNone = 0,
  DecorationLineUnderline = 1,
  DecorationLineOverline = 2,
  DecorationLineLineThrough = 3,
};

typedef SWIFT_ENUM_NAMED(NSInteger, Direction, "Direction", open) {
  DirectionInherit = 0,
  DirectionLTR = 1,
  DirectionRTL = 2,
};

typedef SWIFT_ENUM_NAMED(NSInteger, Display, "Display", open) {
  DisplayNone = 0,
  DisplayFlex = 1,
  DisplayGrid = 2,
  DisplayBlock = 3,
};

typedef SWIFT_ENUM_NAMED(NSInteger, FlexDirection, "FlexDirection", open) {
  FlexDirectionRow = 0,
  FlexDirectionColumn = 1,
  FlexDirectionRowReverse = 2,
  FlexDirectionColumnReverse = 3,
};

typedef SWIFT_ENUM_NAMED(NSInteger, FlexWrap, "FlexWrap", open) {
  FlexWrapNoWrap = 0,
  FlexWrapWrap = 1,
  FlexWrapWrapReverse = 2,
};

typedef SWIFT_ENUM_NAMED(NSInteger, FontStyle, "FontStyle", open) {
  FontStyleNormal = 0,
  FontStyleItalic = 1,
  FontStyleOblique = 2,
};

typedef SWIFT_ENUM_NAMED(NSInteger, FlexGridAutoFlowWrap, "GridAutoFlow", open) {
  FlexGridAutoFlowWrapRow = 0,
  FlexGridAutoFlowWrapColumn = 1,
  FlexGridAutoFlowWrapRowDense = 2,
  FlexGridAutoFlowWrapColumnDense = 3,
};

enum GridPlacementCompatType : NSInteger;
@class NSString;

SWIFT_CLASS_NAMED("GridPlacementCompat")
@interface GridPlacementCompat : NSObject
- (nonnull instancetype)initWithSpan:(int16_t)span OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithLine:(int16_t)line OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) enum GridPlacementCompatType type;
@property (nonatomic, readonly) int16_t value;
@property (nonatomic, readonly, copy) NSString * _Nonnull cssValue;
@property (nonatomic, readonly, copy) NSString * _Nullable jsonValue;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) GridPlacementCompat * _Nonnull Auto;)
+ (GridPlacementCompat * _Nonnull)Auto SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM_NAMED(NSInteger, GridPlacementCompatType, "GridPlacementCompatType", open) {
  GridPlacementCompatTypeAuto = 0,
  GridPlacementCompatTypeLine = 1,
  GridPlacementCompatTypeSpan = 2,
};


SWIFT_CLASS_NAMED("GridTrackRepetition")
@interface GridTrackRepetition : NSObject
@property (nonatomic, readonly) int32_t type;
@property (nonatomic, readonly) uint16_t value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) GridTrackRepetition * _Nonnull AutoFill;)
+ (GridTrackRepetition * _Nonnull)AutoFill SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) GridTrackRepetition * _Nonnull AutoFit;)
+ (GridTrackRepetition * _Nonnull)AutoFit SWIFT_WARN_UNUSED_RESULT;
+ (GridTrackRepetition * _Nonnull)Count:(uint16_t)value SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM_NAMED(NSInteger, JustifyContent, "JustifyContent", open) {
  JustifyContentNormal = -1,
  JustifyContentStart = 0,
  JustifyContentEnd = 1,
  JustifyContentCenter = 2,
  JustifyContentStretch = 3,
  JustifyContentSpaceBetween = 4,
  JustifyContentSpaceAround = 5,
  JustifyContentSpaceEvenly = 6,
  JustifyContentFlexStart = 7,
  JustifyContentFlexEnd = 8,
};

typedef SWIFT_ENUM_NAMED(NSInteger, JustifyItems, "JustifyItems", open) {
  JustifyItemsNormal = -1,
  JustifyItemsStart = 0,
  JustifyItemsEnd = 1,
  JustifyItemsCenter = 2,
  JustifyItemsBaseline = 3,
  JustifyItemsStretch = 4,
  JustifyItemsFlexStart = 5,
  JustifyItemsFlexEnd = 6,
};

typedef SWIFT_ENUM_NAMED(NSInteger, JustifySelf, "JustifySelf", open) {
  JustifySelfNormal = -1,
  JustifySelfStart = 0,
  JustifySelfEnd = 1,
  JustifySelfCenter = 2,
  JustifySelfBaseline = 3,
  JustifySelfStretch = 4,
  JustifySelfFlexStart = 5,
  JustifySelfFlexEnd = 6,
};


SWIFT_CLASS_NAMED("LineGridPlacementCompat")
@interface LineGridPlacementCompat : NSObject
@property (nonatomic, readonly, strong) GridPlacementCompat * _Nonnull start;
@property (nonatomic, readonly, strong) GridPlacementCompat * _Nonnull end;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM_NAMED(NSInteger, MasonBoxSizing, "MasonBoxSizing", open) {
  MasonBoxSizingBorderBox = 0,
  MasonBoxSizingContentBox = 1,
};

enum MasonDimensionCompatType : NSInteger;

SWIFT_CLASS_NAMED("MasonDimensionCompat")
@interface MasonDimensionCompat : NSObject
- (nonnull instancetype)initWithPoints:(float)points OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithPercent:(float)percent OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) enum MasonDimensionCompatType type;
@property (nonatomic, readonly) float value;
@property (nonatomic, readonly, copy) NSString * _Nonnull cssValue;
@property (nonatomic, readonly, copy) NSString * _Nullable jsonValue;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) MasonDimensionCompat * _Nonnull Auto;)
+ (MasonDimensionCompat * _Nonnull)Auto SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) MasonDimensionCompat * _Nonnull Zero;)
+ (MasonDimensionCompat * _Nonnull)Zero SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM_NAMED(NSInteger, MasonDimensionCompatType, "MasonDimensionCompatType", open) {
  MasonDimensionCompatTypeAuto = 0,
  MasonDimensionCompatTypePoints = 1,
  MasonDimensionCompatTypePercent = 2,
};


SWIFT_CLASS_NAMED("MasonDimensionRectCompat")
@interface MasonDimensionRectCompat : NSObject
@property (nonatomic, strong) MasonDimensionCompat * _Nonnull left;
@property (nonatomic, strong) MasonDimensionCompat * _Nonnull right;
@property (nonatomic, strong) MasonDimensionCompat * _Nonnull top;
@property (nonatomic, strong) MasonDimensionCompat * _Nonnull bottom;
- (nonnull instancetype)init:(MasonDimensionCompat * _Nonnull)left :(MasonDimensionCompat * _Nonnull)right :(MasonDimensionCompat * _Nonnull)top :(MasonDimensionCompat * _Nonnull)bottom OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("MasonDimensionSizeCompat")
@interface MasonDimensionSizeCompat : NSObject
@property (nonatomic, strong) MasonDimensionCompat * _Nonnull width;
@property (nonatomic, strong) MasonDimensionCompat * _Nonnull height;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("MasonLayout")
@interface MasonLayout : NSObject
@property (nonatomic, readonly) NSInteger order;
@property (nonatomic, readonly) float x;
@property (nonatomic, readonly) float y;
@property (nonatomic, readonly) float width;
@property (nonatomic, readonly) float height;
@property (nonatomic, readonly, copy) NSArray<MasonLayout *> * _Nonnull children;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

enum MasonLengthPercentageAutoCompatType : NSInteger;

SWIFT_CLASS_NAMED("MasonLengthPercentageAutoCompat")
@interface MasonLengthPercentageAutoCompat : NSObject
- (nonnull instancetype)initWithPoints:(float)points OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithPercent:(float)percent OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) enum MasonLengthPercentageAutoCompatType type;
@property (nonatomic, readonly) float value;
@property (nonatomic, readonly, copy) NSString * _Nonnull cssValue;
@property (nonatomic, readonly, copy) NSString * _Nullable jsonValue;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) MasonLengthPercentageAutoCompat * _Nonnull Auto;)
+ (MasonLengthPercentageAutoCompat * _Nonnull)Auto SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) MasonLengthPercentageAutoCompat * _Nonnull Zero;)
+ (MasonLengthPercentageAutoCompat * _Nonnull)Zero SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM_NAMED(NSInteger, MasonLengthPercentageAutoCompatType, "MasonLengthPercentageAutoCompatType", open) {
  MasonLengthPercentageAutoCompatTypeAuto = 0,
  MasonLengthPercentageAutoCompatTypePoints = 1,
  MasonLengthPercentageAutoCompatTypePercent = 2,
};


SWIFT_CLASS_NAMED("MasonLengthPercentageAutoRectCompat")
@interface MasonLengthPercentageAutoRectCompat : NSObject
@property (nonatomic, strong) MasonLengthPercentageAutoCompat * _Nonnull left;
@property (nonatomic, strong) MasonLengthPercentageAutoCompat * _Nonnull right;
@property (nonatomic, strong) MasonLengthPercentageAutoCompat * _Nonnull top;
@property (nonatomic, strong) MasonLengthPercentageAutoCompat * _Nonnull bottom;
- (nonnull instancetype)init:(MasonLengthPercentageAutoCompat * _Nonnull)left :(MasonLengthPercentageAutoCompat * _Nonnull)right :(MasonLengthPercentageAutoCompat * _Nonnull)top :(MasonLengthPercentageAutoCompat * _Nonnull)bottom OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("MasonLengthPercentageAutoSizeCompat")
@interface MasonLengthPercentageAutoSizeCompat : NSObject
@property (nonatomic, strong) MasonLengthPercentageAutoCompat * _Nonnull width;
@property (nonatomic, strong) MasonLengthPercentageAutoCompat * _Nonnull height;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

enum MasonLengthPercentageCompatType : NSInteger;

SWIFT_CLASS_NAMED("MasonLengthPercentageCompat")
@interface MasonLengthPercentageCompat : NSObject
- (nonnull instancetype)initWithPoints:(float)points OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithPercent:(float)percent OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) enum MasonLengthPercentageCompatType type;
@property (nonatomic, readonly) float value;
@property (nonatomic, readonly, copy) NSString * _Nonnull cssValue;
@property (nonatomic, readonly, copy) NSString * _Nullable jsonValue;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) MasonLengthPercentageCompat * _Nonnull Zero;)
+ (MasonLengthPercentageCompat * _Nonnull)Zero SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM_NAMED(NSInteger, MasonLengthPercentageCompatType, "MasonLengthPercentageCompatType", open) {
  MasonLengthPercentageCompatTypePoints = 0,
  MasonLengthPercentageCompatTypePercent = 1,
};


SWIFT_CLASS_NAMED("MasonLengthPercentageRectCompat")
@interface MasonLengthPercentageRectCompat : NSObject
@property (nonatomic, strong) MasonLengthPercentageCompat * _Nonnull left;
@property (nonatomic, strong) MasonLengthPercentageCompat * _Nonnull right;
@property (nonatomic, strong) MasonLengthPercentageCompat * _Nonnull top;
@property (nonatomic, strong) MasonLengthPercentageCompat * _Nonnull bottom;
- (nonnull instancetype)init:(MasonLengthPercentageCompat * _Nonnull)left :(MasonLengthPercentageCompat * _Nonnull)right :(MasonLengthPercentageCompat * _Nonnull)top :(MasonLengthPercentageCompat * _Nonnull)bottom OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("MasonLengthPercentageSizeCompat")
@interface MasonLengthPercentageSizeCompat : NSObject
@property (nonatomic, strong) MasonLengthPercentageCompat * _Nonnull width;
@property (nonatomic, strong) MasonLengthPercentageCompat * _Nonnull height;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class MasonStyle;
@class NSCMason;

SWIFT_CLASS_NAMED("MasonNode")
@interface MasonNode : NSObject
@property (nonatomic, readonly) void * _Nullable nativePtr;
@property (nonatomic, readonly, strong) MasonLayout * _Nullable layoutCache;
@property (nonatomic) id _Nullable data;
@property (nonatomic, strong) MasonStyle * _Nonnull style;
@property (nonatomic, readonly, strong) MasonNode * _Nullable owner;
@property (nonatomic, readonly, copy) NSArray<MasonNode *> * _Nonnull children;
- (nonnull instancetype)initWithMason:(NSCMason * _Nonnull)doc children:(NSArray<MasonNode *> * _Nonnull)nodes OBJC_DESIGNATED_INITIALIZER;
- (MasonLayout * _Nonnull)layout;
@property (nonatomic, readonly) BOOL isDirty;
- (void)markDirty;
- (MasonNode * _Nullable)getRoot SWIFT_WARN_UNUSED_RESULT;
- (void)compute;
- (void)compute:(float)width :(float)height;
- (void)computeMaxContent;
- (void)computeMinContent;
- (void)computeWithSize:(float)width :(float)height;
- (void)computeWithViewSize;
- (void)computeWithViewSizeWithLayout:(BOOL)layout;
- (void)computeWithMaxContent;
- (void)computeWithMinContent;
- (void)attachAndApply;
- (void)setChildrenWithValue:(NSArray<MasonNode *> * _Nonnull)value;
- (void)addChildren:(NSArray<MasonNode *> * _Nonnull)children;
- (void)configure:(SWIFT_NOESCAPE void (^ _Nonnull)(MasonNode * _Nonnull))block;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSMutableData;
@class NSData;
enum Position : NSInteger;
enum Overflow : NSInteger;
enum MasonTextAlign : NSInteger;
@class MinMax;
@class TrackSizingFunction;

SWIFT_CLASS_NAMED("MasonStyle")
@interface MasonStyle : NSObject
@property (nonatomic, strong) NSMutableData * _Nonnull valuesCompat;
@property (nonatomic, copy) NSData * _Nonnull values;
- (nonnull instancetype)initWithNode:(MasonNode * _Nonnull)node OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic) enum Display display;
@property (nonatomic) enum Position position;
@property (nonatomic) enum Direction direction;
@property (nonatomic) enum FlexDirection flexDirection;
@property (nonatomic) enum FlexWrap flexWrap;
@property (nonatomic) enum Overflow overflowX;
@property (nonatomic) enum Overflow overflowY;
@property (nonatomic) enum AlignItems alignItems;
@property (nonatomic) enum AlignSelf alignSelf;
@property (nonatomic) enum AlignContent alignContent;
@property (nonatomic) enum JustifyItems justifyItems;
@property (nonatomic) enum JustifySelf justifySelf;
@property (nonatomic) enum JustifyContent justifyContent;
@property (nonatomic, strong) MasonLengthPercentageAutoRectCompat * _Nonnull insetCompat;
- (void)setInsetLeft:(float)value :(NSInteger)type;
- (void)setInsetRight:(float)value :(NSInteger)type;
- (void)setInsetTop:(float)value :(NSInteger)type;
- (void)setInsetBottom:(float)value :(NSInteger)type;
- (void)setInsetWithValueType:(float)value :(NSInteger)type;
@property (nonatomic, strong) MasonLengthPercentageAutoRectCompat * _Nonnull marginCompat;
- (void)setMarginLeft:(float)value :(NSInteger)type;
- (void)setMarginRight:(float)value :(NSInteger)type;
- (void)setMarginTop:(float)value :(NSInteger)type;
- (void)setMarginBottom:(float)value :(NSInteger)type;
- (void)setMarginWithValueType:(float)value :(NSInteger)type;
@property (nonatomic, strong) MasonLengthPercentageRectCompat * _Nonnull paddingCompat;
- (void)setPaddingLeft:(float)value :(NSInteger)type;
- (void)setPaddingRight:(float)value :(NSInteger)type;
- (void)setPaddingTop:(float)value :(NSInteger)type;
- (void)setPaddingBottom:(float)value :(NSInteger)type;
- (void)setPaddingWithValueType:(float)value :(NSInteger)type;
@property (nonatomic, strong) MasonLengthPercentageRectCompat * _Nonnull borderCompat;
- (void)setBorderLeft:(float)value :(NSInteger)type;
- (void)setBorderRight:(float)value :(NSInteger)type;
- (void)setBorderTop:(float)value :(NSInteger)type;
- (void)setBorderBottom:(float)value :(NSInteger)type;
- (void)setBorderWithValueType:(float)value :(NSInteger)type;
@property (nonatomic) float flexGrow;
@property (nonatomic) float flexShrink;
- (void)setFlexBasis:(float)value :(NSInteger)type;
- (void)setScrollBarWidth:(float)value;
@property (nonatomic) enum MasonTextAlign textAlign;
@property (nonatomic) enum MasonBoxSizing boxSizing;
@property (nonatomic, strong) MasonDimensionSizeCompat * _Nonnull minSizeCompat;
- (void)setMinSizeWidth:(float)value :(NSInteger)type;
- (void)setMinSizeHeight:(float)value :(NSInteger)type;
- (void)setMinSizeWidthHeight:(float)value :(NSInteger)type;
@property (nonatomic, strong) MasonDimensionSizeCompat * _Nonnull sizeCompat;
@property (nonatomic, strong) MasonDimensionCompat * _Nonnull sizeCompatWidth;
@property (nonatomic, strong) MasonDimensionCompat * _Nonnull sizeCompatHeight;
- (void)setSizeWidth:(float)value :(NSInteger)type;
- (void)setSizeHeight:(float)value :(NSInteger)type;
- (void)setSizeWidthHeight:(float)value :(NSInteger)type;
@property (nonatomic, strong) MasonDimensionSizeCompat * _Nonnull maxSizeCompat;
- (void)setMaxSizeWidth:(float)value :(NSInteger)type;
- (void)setMaxSizeHeight:(float)value :(NSInteger)type;
- (void)setMaxSizeWidthHeight:(float)value :(NSInteger)type;
@property (nonatomic, strong) MasonLengthPercentageSizeCompat * _Nonnull gapCompat;
- (void)setGapRow:(float)value :(NSInteger)type;
- (void)setGapColumn:(float)value :(NSInteger)type;
- (void)setRowGap:(float)value :(NSInteger)type;
- (void)setColumnGap:(float)value :(NSInteger)type;
@property (nonatomic, copy) NSArray<MinMax *> * _Nonnull gridAutoRows;
@property (nonatomic, copy) NSArray<MinMax *> * _Nonnull gridAutoColumns;
@property (nonatomic) enum FlexGridAutoFlowWrap gridAutoFlow;
@property (nonatomic, strong) LineGridPlacementCompat * _Nonnull gridColumnCompat;
@property (nonatomic, strong) GridPlacementCompat * _Nonnull gridColumnStartCompat;
@property (nonatomic, strong) GridPlacementCompat * _Nonnull gridColumnEndCompat;
@property (nonatomic, strong) LineGridPlacementCompat * _Nonnull gridRowCompat;
@property (nonatomic, strong) GridPlacementCompat * _Nonnull gridRowStartCompat;
@property (nonatomic, strong) GridPlacementCompat * _Nonnull gridRowEndCompat;
@property (nonatomic, copy) NSArray<TrackSizingFunction *> * _Nonnull gridTemplateRows;
@property (nonatomic, copy) NSArray<TrackSizingFunction *> * _Nonnull gridTemplateColumns;
- (void)updateNativeStyle;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSCoder;
@class NSMutableAttributedString;
@class UIFont;
enum TextTransform : NSInteger;
@class UIColor;
enum TextWrap : NSInteger;

SWIFT_CLASS_NAMED("MasonText")
@interface MasonText : UIView
@property (nonatomic, readonly, strong) MasonText * _Nullable owner;
@property (nonatomic, readonly, strong) MasonNode * _Nonnull node;
@property (nonatomic, readonly, copy) NSData * _Nonnull textValues;
- (nonnull instancetype)initWithMason:(NSCMason * _Nonnull)mason OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNode:(MasonNode * _Nonnull)masonNode OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
@property (nonatomic, readonly, strong) UIView * _Nonnull uiView;
@property (nonatomic, readonly, strong) MasonStyle * _Nonnull style;
- (void)markNodeDirty;
- (BOOL)isNodeDirty SWIFT_WARN_UNUSED_RESULT;
- (void)configure:(SWIFT_NOESCAPE void (^ _Nonnull)(MasonNode * _Nonnull))block;
- (void)updateText:(NSString * _Nullable)value;
@property (nonatomic, strong) NSMutableAttributedString * _Nonnull txtToRender;
@property (nonatomic, readonly, strong) UIFont * _Nonnull font;
- (void)invalidateStyle:(int64_t)state;
@property (nonatomic) enum TextTransform textTransform;
@property (nonatomic) CGFloat fontSize;
@property (nonatomic) enum FontStyle fontStyle;
- (void)setFontStyle:(enum FontStyle)style slant:(int32_t)slant;
@property (nonatomic, copy) NSString * _Nonnull fontWeight;
@property (nonatomic) uint32_t color;
@property (nonatomic) uint32_t backgroundColorValue;
- (void)setColorWithUi:(UIColor * _Nonnull)color;
- (void)setBackgroundColorWithUi:(UIColor * _Nonnull)color;
- (void)setDecorationColorWithUi:(UIColor * _Nonnull)color;
@property (nonatomic) uint32_t decorationColor;
@property (nonatomic) enum DecorationLine decorationLine;
@property (nonatomic) enum TextWrap textWrap;
- (void)drawRect:(CGRect)rect;
- (void)addView:(UIView * _Nonnull)view :(NSInteger)index;
- (void)removeView:(UIView * _Nonnull)view;
@property (nonatomic, copy) NSString * _Nullable text;
- (void)syncStyle:(NSString * _Nonnull)state :(NSString * _Nonnull)textState;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end

typedef SWIFT_ENUM_NAMED(NSInteger, MasonTextAlign, "MasonTextAlign", open) {
  MasonTextAlignAuto = 0,
  MasonTextAlignLeft = 1,
  MasonTextAlignRight = 2,
  MasonTextAlignCenter = 3,
  MasonTextAlignJustify = 4,
  MasonTextAlignStart = 5,
  MasonTextAlignEnd = 6,
};


SWIFT_CLASS_NAMED("MasonUIView")
@interface MasonUIView : UIView
@property (nonatomic, readonly, strong) UIView * _Nonnull uiView;
- (void)markNodeDirty;
- (BOOL)isNodeDirty SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, strong) MasonNode * _Nonnull node;
@property (nonatomic, readonly, strong) NSCMason * _Nonnull mason;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
+ (MasonUIView * _Nonnull)createGridView:(NSCMason * _Nonnull)mason SWIFT_WARN_UNUSED_RESULT;
+ (MasonUIView * _Nonnull)createFlexView:(NSCMason * _Nonnull)mason SWIFT_WARN_UNUSED_RESULT;
+ (MasonUIView * _Nonnull)createBlockView:(NSCMason * _Nonnull)mason SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly) int64_t masonPtr;
@property (nonatomic, readonly) int64_t masonNodePtr;
@property (nonatomic, readonly, copy) NSString * _Nonnull masonPtrs;
@property (nonatomic, strong) MasonStyle * _Nonnull style;
- (void)addView:(UIView * _Nonnull)view;
- (void)addView:(UIView * _Nonnull)view at:(NSInteger)at;
- (void)syncStyle:(NSString * _Nonnull)state;
- (void)addSubviews:(NSArray<UIView *> * _Nonnull)views;
- (void)addSubviews:(NSArray<UIView *> * _Nonnull)views at:(NSInteger)index;
- (void)configure:(SWIFT_NOESCAPE void (^ _Nonnull)(MasonNode * _Nonnull))block;
@property (nonatomic) BOOL inBatch;
@property (nonatomic) enum Display display;
@property (nonatomic) enum Position _position;
@property (nonatomic) enum Direction direction;
@property (nonatomic) enum FlexDirection flexDirection;
@property (nonatomic) enum FlexWrap flexWrap;
@property (nonatomic) enum Overflow overflowX;
@property (nonatomic) enum Overflow overflowY;
@property (nonatomic) enum AlignItems alignItems;
@property (nonatomic) enum AlignSelf alignSelf;
@property (nonatomic) enum AlignContent alignContent;
@property (nonatomic) enum JustifyItems justifyItems;
@property (nonatomic) enum JustifySelf justifySelf;
@property (nonatomic) enum JustifyContent justifyContent;
@property (nonatomic) float flexGrow;
@property (nonatomic) float flexShrink;
@property (nonatomic, strong) MasonDimensionCompat * _Nonnull scrollBarWidthCompat;
@property (nonatomic, strong) MasonDimensionCompat * _Nonnull flexBasisCompat;
@property (nonatomic) float aspectRatio;
@property (nonatomic, copy) NSArray<MinMax *> * _Nonnull gridAutoRows;
@property (nonatomic, copy) NSArray<MinMax *> * _Nonnull gridAutoColumns;
@property (nonatomic) enum FlexGridAutoFlowWrap gridAutoFlow;
@property (nonatomic, strong) LineGridPlacementCompat * _Nonnull gridColumnCompat;
@property (nonatomic, strong) GridPlacementCompat * _Nonnull gridColumnStartCompat;
@property (nonatomic, strong) GridPlacementCompat * _Nonnull gridColumnEndCompat;
@property (nonatomic, strong) LineGridPlacementCompat * _Nonnull gridRowCompat;
@property (nonatomic, strong) GridPlacementCompat * _Nonnull gridRowStartCompat;
@property (nonatomic, strong) GridPlacementCompat * _Nonnull gridRowEndCompat;
@property (nonatomic, copy) NSArray<TrackSizingFunction *> * _Nonnull gridTemplateRows;
@property (nonatomic, copy) NSArray<TrackSizingFunction *> * _Nonnull gridTemplateColumns;
- (void)setPadding:(float)left :(float)right :(float)top :(float)bottom;
- (MasonLengthPercentageRectCompat * _Nonnull)getPadding SWIFT_WARN_UNUSED_RESULT;
- (void)setPaddingLeft:(float)left :(NSInteger)type;
- (void)setPaddingRight:(float)right :(NSInteger)type;
- (void)setPaddingTop:(float)top :(NSInteger)type;
- (void)setPaddingBottom:(float)bottom :(NSInteger)type;
- (MasonLengthPercentageCompat * _Nonnull)getPaddingLeft SWIFT_WARN_UNUSED_RESULT;
- (MasonLengthPercentageCompat * _Nonnull)getPaddingRight SWIFT_WARN_UNUSED_RESULT;
- (MasonLengthPercentageCompat * _Nonnull)getPaddingTop SWIFT_WARN_UNUSED_RESULT;
- (MasonLengthPercentageCompat * _Nonnull)getPaddingBottom SWIFT_WARN_UNUSED_RESULT;
- (void)setBorder:(float)left :(float)top :(float)right :(float)bottom;
- (MasonLengthPercentageRectCompat * _Nonnull)getBorder SWIFT_WARN_UNUSED_RESULT;
- (void)setBorderLeft:(float)left :(NSInteger)type;
- (void)setBorderRight:(float)right :(NSInteger)type;
- (void)setBorderTop:(float)top :(NSInteger)type;
- (void)setBorderBottom:(float)bottom :(NSInteger)type;
- (MasonLengthPercentageCompat * _Nonnull)getBorderLeft SWIFT_WARN_UNUSED_RESULT;
- (MasonLengthPercentageCompat * _Nonnull)getBorderRight SWIFT_WARN_UNUSED_RESULT;
- (MasonLengthPercentageCompat * _Nonnull)getBorderBottom SWIFT_WARN_UNUSED_RESULT;
- (MasonLengthPercentageCompat * _Nonnull)getBorderTop SWIFT_WARN_UNUSED_RESULT;
- (void)setMargin:(float)left :(float)top :(float)right :(float)bottom;
- (MasonLengthPercentageAutoRectCompat * _Nonnull)getMargin SWIFT_WARN_UNUSED_RESULT;
- (void)setMarginLeft:(float)left :(NSInteger)type;
- (void)setMarginRight:(float)right :(NSInteger)type;
- (void)setMarginTop:(float)top :(NSInteger)type;
- (void)setMarginBottom:(float)bottom :(NSInteger)type;
- (MasonLengthPercentageAutoCompat * _Nonnull)getMarginLeft SWIFT_WARN_UNUSED_RESULT;
- (MasonLengthPercentageAutoCompat * _Nonnull)getMarginRight SWIFT_WARN_UNUSED_RESULT;
- (MasonLengthPercentageAutoCompat * _Nonnull)getMarginTop SWIFT_WARN_UNUSED_RESULT;
- (MasonLengthPercentageAutoCompat * _Nonnull)getMarginBottom SWIFT_WARN_UNUSED_RESULT;
- (void)setInset:(float)left :(float)top :(float)right :(float)bottom;
- (MasonLengthPercentageAutoRectCompat * _Nonnull)getInset SWIFT_WARN_UNUSED_RESULT;
- (void)setInsetLeft:(float)left :(NSInteger)type;
- (void)setInsetRight:(float)right :(NSInteger)type;
- (void)setInsetTop:(float)top :(NSInteger)type;
- (void)setInsetBottom:(float)bottom :(NSInteger)type;
- (MasonLengthPercentageAutoCompat * _Nonnull)getInsetLeft SWIFT_WARN_UNUSED_RESULT;
- (MasonLengthPercentageAutoCompat * _Nonnull)getInsetRight SWIFT_WARN_UNUSED_RESULT;
- (MasonLengthPercentageAutoCompat * _Nonnull)getInsetTop SWIFT_WARN_UNUSED_RESULT;
- (MasonLengthPercentageAutoCompat * _Nonnull)getInsetBottom SWIFT_WARN_UNUSED_RESULT;
- (void)setMinSize:(float)width :(float)height;
- (MasonDimensionSizeCompat * _Nonnull)getMinSize SWIFT_WARN_UNUSED_RESULT;
- (void)setMinSizeWidth:(float)width :(NSInteger)type;
- (void)setMinSizeHeight:(float)height :(NSInteger)type;
- (MasonDimensionCompat * _Nonnull)getMinSizeWidth SWIFT_WARN_UNUSED_RESULT;
- (MasonDimensionCompat * _Nonnull)getMinSizeHeight SWIFT_WARN_UNUSED_RESULT;
- (void)setSize:(float)width :(float)height;
- (void)setSizeWidth:(float)width :(NSInteger)type;
- (void)setSizeHeight:(float)height :(NSInteger)type;
- (MasonDimensionSizeCompat * _Nonnull)getSize SWIFT_WARN_UNUSED_RESULT;
- (MasonDimensionCompat * _Nonnull)getSizeWidth SWIFT_WARN_UNUSED_RESULT;
- (MasonDimensionCompat * _Nonnull)getSizeHeight SWIFT_WARN_UNUSED_RESULT;
- (void)setMaxSize:(float)width :(float)height;
- (MasonDimensionSizeCompat * _Nonnull)getMaxSize SWIFT_WARN_UNUSED_RESULT;
- (void)setMaxSizeWidth:(float)width :(NSInteger)type;
- (void)setMaxSizeHeight:(float)height :(NSInteger)type;
- (MasonDimensionCompat * _Nonnull)getMaxSizeWidth SWIFT_WARN_UNUSED_RESULT;
- (MasonDimensionCompat * _Nonnull)getMaxSizeHeight SWIFT_WARN_UNUSED_RESULT;
- (void)setGap:(float)width :(float)height;
- (void)setGapWithWidthHeightType:(float)width :(NSInteger)width_type :(float)height :(NSInteger)height_type;
- (MasonLengthPercentageSizeCompat * _Nonnull)getGap SWIFT_WARN_UNUSED_RESULT;
- (void)setRowGap:(float)row :(NSInteger)type;
- (void)setColumnGap:(float)column :(NSInteger)type;
- (MasonLengthPercentageCompat * _Nonnull)getRowGap SWIFT_WARN_UNUSED_RESULT;
- (MasonLengthPercentageCompat * _Nonnull)getColumnGap SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS_NAMED("MaxSizing")
@interface MaxSizing : NSObject
@property (nonatomic, readonly) float value;
+ (MaxSizing * _Nonnull)Points:(float)points SWIFT_WARN_UNUSED_RESULT;
+ (MaxSizing * _Nonnull)Percent:(float)percent SWIFT_WARN_UNUSED_RESULT;
+ (MaxSizing * _Nonnull)FitContent:(float)fit SWIFT_WARN_UNUSED_RESULT;
+ (MaxSizing * _Nonnull)FitContentPercent:(float)fit SWIFT_WARN_UNUSED_RESULT;
+ (MaxSizing * _Nonnull)Fraction:(float)flex SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) MaxSizing * _Nonnull Auto;)
+ (MaxSizing * _Nonnull)Auto SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) MaxSizing * _Nonnull MinContent;)
+ (MaxSizing * _Nonnull)MinContent SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) MaxSizing * _Nonnull MaxContent;)
+ (MaxSizing * _Nonnull)MaxContent SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, copy) NSString * _Nonnull cssValue;
@property (nonatomic, readonly, copy) NSString * _Nullable jsonValue;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("MeasureOutput")
@interface MeasureOutput : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class MinSizing;

SWIFT_CLASS_NAMED("MinMax")
@interface MinMax : NSObject
- (nonnull instancetype)init:(MinSizing * _Nonnull)min :(MaxSizing * _Nonnull)max OBJC_DESIGNATED_INITIALIZER;
+ (MinMax * _Nonnull)PointsWithPoints:(float)points SWIFT_WARN_UNUSED_RESULT;
+ (MinMax * _Nonnull)PercentWithPercent:(float)percent SWIFT_WARN_UNUSED_RESULT;
+ (MinMax * _Nonnull)FlexWithFlex:(float)flex SWIFT_WARN_UNUSED_RESULT;
+ (MinMax * _Nonnull)FitContentWithFit:(float)fit SWIFT_WARN_UNUSED_RESULT;
+ (MinMax * _Nonnull)FitContentPercentWithFit:(float)fit SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) MinMax * _Nonnull Auto;)
+ (MinMax * _Nonnull)Auto SWIFT_WARN_UNUSED_RESULT;
+ (MinMax * _Nullable)fromTypeValue:(NSInteger)minType :(float)minValue :(NSInteger)maxType :(float)maxValue SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, copy) NSString * _Nonnull cssValue;
@property (nonatomic, readonly, copy) NSString * _Nullable jsonValue;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("MinSizing")
@interface MinSizing : NSObject
@property (nonatomic, readonly) float value;
+ (MinSizing * _Nonnull)Points:(float)points SWIFT_WARN_UNUSED_RESULT;
+ (MinSizing * _Nonnull)Percent:(float)percent SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) MinSizing * _Nonnull Auto;)
+ (MinSizing * _Nonnull)Auto SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) MinSizing * _Nonnull MinContent;)
+ (MinSizing * _Nonnull)MinContent SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) MinSizing * _Nonnull MaxContent;)
+ (MinSizing * _Nonnull)MaxContent SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, copy) NSString * _Nonnull cssValue;
@property (nonatomic, readonly, copy) NSString * _Nullable jsonValue;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("NSCMason")
@interface NSCMason : NSObject
@property (nonatomic, readonly) void * _Nullable nativePtr;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) NSCMason * _Nonnull shared;)
+ (NSCMason * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
+ (void)setShared:(NSCMason * _Nonnull)value;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (MasonNode * _Nonnull)nodeForView:(UIView * _Nonnull)view :(BOOL)isLeaf SWIFT_WARN_UNUSED_RESULT;
- (void)clear;
- (MasonUIView * _Nonnull)createView SWIFT_WARN_UNUSED_RESULT;
- (MasonText * _Nonnull)createTextView SWIFT_WARN_UNUSED_RESULT;
- (MasonNode * _Nonnull)createNode SWIFT_WARN_UNUSED_RESULT;
- (void)printTree:(MasonNode * _Nonnull)node;
- (MasonNode * _Nonnull)createTextNode SWIFT_WARN_UNUSED_RESULT;
@end

typedef SWIFT_ENUM_NAMED(NSInteger, Overflow, "Overflow", open) {
  OverflowUnset = 0,
  OverflowVisible = 1,
  OverflowHidden = 2,
  OverflowScroll = 3,
};

typedef SWIFT_ENUM_NAMED(NSInteger, Position, "Position", open) {
  PositionRelative = 0,
  PositionAbsolute = 1,
};

typedef SWIFT_ENUM_NAMED(NSInteger, TextTransform, "TextTransform", open) {
  TextTransformNone = 0,
  TextTransformCapitalize = 1,
  TextTransformUppercase = 2,
  TextTransformLowercase = 3,
  TextTransformFullWidth = 4,
  TextTransformFullSizeKana = 5,
  TextTransformMathAuto = 6,
};

typedef SWIFT_ENUM_NAMED(NSInteger, TextWrap, "TextWrap", open) {
  TextWrapNoWrap = 0,
  TextWrapWrap = 1,
  TextWrapBalance = 2,
};


SWIFT_CLASS_NAMED("TrackSizingFunction")
@interface TrackSizingFunction : NSObject
@property (nonatomic, readonly) BOOL isRepeating;
@property (nonatomic, readonly) id _Nullable value;
+ (TrackSizingFunction * _Nonnull)Single:(MinMax * _Nonnull)value SWIFT_WARN_UNUSED_RESULT;
+ (TrackSizingFunction * _Nonnull)AutoRepeat:(GridTrackRepetition * _Nonnull)gridTrackRepetition :(NSArray<MinMax *> * _Nonnull)value SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
